In [1]:
%reload_ext autoreload
%autoreload 2
import numpy as np
import pynocular as pn
from matplotlib import pyplot as plt
from uncertainties import unumpy

In [7]:
g2d = pn.Grid(x=np.arange(10), y=np.arange(20))

In [8]:
b = pn.GridArray(np.random.rand(g2d.size).reshape(g2d.shape), grid=g2d)

In [9]:
f = np.sum(np.cos(b) -1.2 / b, axis='y')

In [10]:
f[f>-50] *= 33

In [11]:
f[0:2] *= 0

In [35]:
a = pn.GridArray(np.arange(10), x=10)

In [36]:
a[[2,7]] *= 0

In [37]:
a.grid

Grid(
Axis("x",
points = None,
edges = edges: None)
nbins = 10),)

In [29]:
f[3] *= 4

In [30]:
f[3]

-10589.768427059766

In [31]:
f

GridArray(noname : [-0.0 -0.0 -61.70332547960153 -10589.768427059766 -91.90802491243352
 -80.01776079823661 -194.16952737862783 -158.76165405022584
 -738.1146706682234 -100.16346171492927])

In [51]:
np.cumsum(f, axis='x')

array([  -3232.42700708,   -4700.59616645,   -9339.26622676,
        -12071.69587966,  -15599.19774619,  -17502.98516842,
        -20668.14868224,  -22264.57108904, -274787.72195437,
       -278765.14017335])

In [52]:
f

GridArray(noname : [-3232.4270070783373 -1468.1691593751518 -4638.6700603016
 -2732.4296529080843 -3527.501866527901 -1903.7874222247524
 -3165.163513825642 -1596.4224067958553 -252523.15086532937
 -3977.418218984074])

In [53]:
a = unumpy.uarray(np.arange(10), np.ones(10))

In [54]:
a = np.arange(10)

In [40]:
g = pn.Grid(x=np.arange(10))

In [55]:
u = pn.GridArray(a, grid=g)

In [56]:
u.grid

Grid(
Axis("x",
points = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
edges = edges: None)
nbins = 10),)

In [60]:
np.max(u)

9

In [54]:
np.amax(np.empty_like(u))

0

In [45]:
u.T

GridArray(noname : [0 1 2 3 4 5 6 7 8 9])

In [61]:
type(l)

pynocular.griddata.GridArray

In [62]:
l

GridArray(noname : [1 1 1 1 1 1 1 1 1 1])

In [63]:
unumpy.cos(u)

GridArray(noname : [1.0 0.5403023058681398 -0.4161468365471424 -0.9899924966004454
 -0.6536436208636119 0.28366218546322625 0.960170286650366
 0.7539022543433046 -0.14550003380861354 -0.9111302618846769])

In [64]:
np.ones_like(u)

GridArray(noname : [1 1 1 1 1 1 1 1 1 1])

In [65]:
np.sqrt(u)

GridArray(noname : [0.0 1.0 1.4142135623730951 1.7320508075688772 2.0 2.23606797749979
 2.449489742783178 2.6457513110645907 2.8284271247461903 3.0])

In [66]:
np.asarray(10 / u)

array([10.        , 10.        ,  5.        ,  3.33333333,  2.5       ,
        2.        ,  1.66666667,  1.42857143,  1.25      ,  1.11111111])

In [67]:
u

GridArray(noname : [0 1 2 3 4 5 6 7 8 9])

In [68]:
np.sqrt(u[u>2])

GridArray(noname : [-- -- -- 1.7320508075688772 2.0 2.23606797749979 2.449489742783178
 2.6457513110645907 2.8284271247461903 3.0])

In [62]:
u[0:3]

GridArray(noname : [0 1 2])

In [63]:
g = pn.GridData(x=np.arange(20), y=np.arange(5))
#g = pn.GridData(y=np.arange(5))

In [64]:
g.grid['x'].edges = pn.edges(points=g.grid['x'].points)

In [65]:
e = pn.edges(points=np.arange(11))

In [66]:
e[0,0]

-0.5

In [67]:
a = pn.GridArray(np.random.rand(g.grid.size).reshape(g.shape), grid=g.grid)

In [68]:
a.astype(np.int)

GridArray(noname : [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]])

In [69]:
np.ones_like(a)

GridArray(noname : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]])

In [70]:
np.all(np.abs(-a) == a)

True

In [71]:
np.abs(-a)

GridArray(noname : [[0.5177375784780318 0.7482326780888998 0.8499712068554451
  0.8518404861918178 0.019097036433522008]
 [0.2825374295847046 0.3078454393308818 0.22770422399035217
  0.9859818202784648 0.4670272354156978]
 [0.975256130012089 0.49466409786460797 0.6126701545749088
  0.3093481853529876 0.1375260306816375]
 [0.5543585190346046 0.8086064142542737 0.43295253799597966
  0.06895191445469673 0.8521442534199218]
 [0.6553369653470313 0.21350804235552734 0.030903727007074
  0.3603018218424344 0.34186607738001784]
 [0.5000146221488848 0.376138475042576 0.3138663695188739
  0.7721956384361709 0.20419148402570597]
 [0.9194679040146779 0.20059368509683395 0.23005955871396477
  0.49256711106822804 0.9359467455647044]
 [0.4399372810911645 0.8194539899075952 0.3699580048857246
  0.24159016746485407 0.749391401134812]
 [0.26918439277572215 0.6402171981879229 0.16347992871767547
  0.3768252307692581 0.7581201473071066]
 [0.0377365690648066 0.10964930531682471 0.6487628759035273
  0.8275656201157255 0.5848968750412501]
 [0.2728338246695904 0.11503790806870173 0.44223876218950975
  0.5724314397254651 0.17301331389297525]
 [0.9611814982883019 0.5162391533561697 0.17170834235621146
  0.1432169199689548 0.6913062232535954]
 [0.7399577311403259 0.9321319185108194 0.7337868607682602
  0.3979076388973811 0.7299725716244725]
 [0.7663881120186093 0.1495134902287205 0.07727664767624987
  0.26727646766190527 0.5371848999183819]
 [0.05115628569152286 0.6980608893994958 0.013004145095709796
  0.043629696189747436 0.18777604746289533]
 [0.4576272745104428 0.025518305402210784 0.5515129354712209
  0.5607512367350058 0.4805068285688505]
 [0.29909591858864903 0.07054671264962253 0.3269378729477447
  0.5867634245234749 0.7091359400441968]
 [0.7766958041153025 0.36543805120134787 0.18194455958956512
  0.7936493321410822 0.8518822062245343]
 [0.04838825278555248 0.7097410777959414 0.360971036285504
  0.17702063359011921 0.7532357148142997]
 [0.3001339653635332 0.5215963427685155 0.5948930912102204
  0.32864982774036344 0.725896955752525]])

In [42]:
np.sum(a, axis='y')

GridArray(noname : [1.40679427 2.44346462 2.83740007 3.61119159 2.7245762  2.83807035
 3.22291119 1.8606903  1.94355386 2.42163508 2.07043905 2.66290041
 2.35678845 2.93104888 2.78202353 3.43038301 1.95638917 2.59294331
 2.44607484 1.51130683])

In [74]:
a

GridArray(noname : [[0.51773758 0.74823268 0.84997121 0.85184049 0.01909704]
 [0.28253743 0.30784544 0.22770422 0.98598182 0.46702724]
 [0.97525613 0.4946641  0.61267015 0.30934819 0.13752603]
 [0.55435852 0.80860641 0.43295254 0.06895191 0.85214425]
 [0.65533697 0.21350804 0.03090373 0.36030182 0.34186608]
 [0.50001462 0.37613848 0.31386637 0.77219564 0.20419148]
 [0.9194679  0.20059369 0.23005956 0.49256711 0.93594675]
 [0.43993728 0.81945399 0.369958   0.24159017 0.7493914 ]
 [0.26918439 0.6402172  0.16347993 0.37682523 0.75812015]
 [0.03773657 0.10964931 0.64876288 0.82756562 0.58489688]
 [0.27283382 0.11503791 0.44223876 0.57243144 0.17301331]
 [0.9611815  0.51623915 0.17170834 0.14321692 0.69130622]
 [0.73995773 0.93213192 0.73378686 0.39790764 0.72997257]
 [0.76638811 0.14951349 0.07727665 0.26727647 0.5371849 ]
 [0.05115629 0.69806089 0.01300415 0.0436297  0.18777605]
 [0.45762727 0.02551831 0.55151294 0.56075124 0.48050683]
 [0.29909592 0.07054671 0.32693787 0.58676342 0.70913594]
 [0.7766958  0.36543805 0.18194456 0.79364933 0.85188221]
 [0.04838825 0.70974108 0.36097104 0.17702063 0.75323571]
 [0.30013397 0.52159634 0.59489309 0.32864983 0.72589696]])

In [84]:
1/np.fabs(a)

GridArray(noname : [[1.9314804286365532 1.336482660118711 1.1765104416884915
  1.1739287063832036 52.364145791995696]
 [3.53935406529987 3.248383351637602 4.39166205385092 1.0142174829527548
  2.141202748293484]
 [1.0253716631215681 2.0215738403430787 1.632199630637849
  3.232603413719499 7.27135070388911]
 [1.8038867730245471 1.236695606628642 2.3097219954610497
  14.502860550116083 1.173510231380059]
 [1.5259325398658896 4.683664319936152 32.358556615876644
  2.7754508564136975 2.9251220468078247]
 [1.9999415131148686 2.658595348127595 3.1860692865339506
  1.2950086095088185 4.897363887487631]
 [1.0875855433710022 4.985201799933349 4.346700504817144
  2.0301802079950173 1.0684368579076036]
 [2.2730512802182328 1.2203247678527551 2.703009495115229
  4.13924130478314 1.334416165552058]
 [3.714925630302703 1.5619699108840093 6.116958869776409
  2.653750116356543 1.319052136461571]
 [26.49949438388683 9.119984819881562 1.5413952264258453
  1.2083633922107124 1.7097030992505724]
 [3.665234694455604 8.692786723857935 2.261221958584165
  1.7469340965611435 5.779902005799348]
 [1.0403862348378814 1.9370867039022677 5.8238288616489315
  6.982415207761558 1.4465369562182646]
 [1.3514285450588253 1.0728095242115592 1.3627935487329659
  2.513146022456473 1.3699144856561003]
 [1.3048219098363547 6.68835968226168 12.940519938047714
  3.741444238424172 1.861556421544866]
 [19.54793993508623 1.432539790132414 76.89855754761692 22.92016876878896
  5.32549285977276]
 [2.1851844409181527 39.187555138883354 1.8131940987849813
  1.783321969689333 2.0811358768374144]
 [3.3434090465651405 14.175004935617658 3.0586850981312668
  1.7042643733496594 1.41016685734145]
 [1.2875053459816908 2.7364419132396898 5.496179727801831
  1.2600023202970907 1.173871214462749]
 [20.666172933166436 1.4089645242254265 2.7703053693456634
  5.649058980974166 1.327605662254792]
 [3.331845493690671 1.9171913566192316 1.6809743040815126
  3.0427522414221673 1.3776059977594437]])

In [81]:
np.cumsum(a, axis='y')

GridArray(noname : [[0.61054606 1.07332914 2.02906309 2.18369999 2.86889444]
 [0.36732215 0.7339393  1.26237548 1.86417865 2.73423492]
 [0.88392344 1.15408384 1.95735726 2.64562632 2.96136072]
 [0.71728274 1.2390976  1.43224394 1.74002479 2.0831975 ]
 [0.54997964 1.51531518 2.31160096 2.89788784 3.07043399]
 [0.6631493  0.77434533 1.24070372 1.55701137 2.40125219]
 [0.76697307 1.54894028 1.59126441 2.21636448 2.6741411 ]
 [0.28262709 0.2908967  1.07018657 1.27340524 2.10458725]
 [0.81628118 1.11090597 1.64860732 1.81273959 1.8312113 ]
 [0.62243436 1.14700875 1.35830487 1.39607147 1.9416003 ]
 [0.15948166 0.46117935 0.57215827 0.64571037 0.79248993]
 [0.0390675  0.94446362 1.11540999 1.31480796 2.09755685]
 [0.45656791 0.84644336 1.44636341 1.69759685 2.44257332]
 [0.53310281 1.20344866 1.7009681  1.80808273 1.99081026]
 [0.26090924 1.19019894 2.08261916 2.85983693 3.42790218]
 [0.94188702 1.51827507 2.13586047 2.47025931 3.01688643]
 [0.32693789 0.71304382 1.54643963 2.53093185 3.38425317]
 [0.81807522 1.56529765 2.0212579  2.72739076 3.51231699]
 [0.00570374 0.40583735 0.98885684 0.9892621  1.17842855]
 [0.48404758 0.93662646 1.32418295 2.04880761 2.51024548]])

In [87]:
np.std(a, axis='y')[::-2]

GridArray(noname : [0.11581801849879496 0.1287997284445286 0.19549379026698813
 0.21600257231565778 0.35298654254783524 0.22463951122359083
 0.32666283022297277 0.2565978870492859 0.1836545553532101
 0.18576078237790697])

In [46]:
a[a > 0.5] *= 10

In [83]:
a.T

GridArray(noname : [[6.10546058e-01 3.67322152e-01 8.83923442e-01 7.17282736e-01
  5.49979636e-01 6.63149299e-01 7.66973071e-01 2.82627090e-01
  8.16281183e-01 6.22434356e-01 1.59481665e-01 3.90675010e-02
  4.56567914e-01 5.33102805e-01 2.60909240e-01 9.41887019e-01
  3.26937892e-01 8.18075217e-01 5.70374280e-03 4.84047585e-01]
 [4.62783078e-01 3.66617148e-01 2.70160396e-01 5.21814862e-01
  9.65335548e-01 1.11196033e-01 7.81967206e-01 8.26960670e-03
  2.94624783e-01 5.24574393e-01 3.01697689e-01 9.05396124e-01
  3.89875445e-01 6.70345860e-01 9.29289702e-01 5.76388053e-01
  3.86105924e-01 7.47222433e-01 4.00133603e-01 4.52578875e-01]
 [9.55733954e-01 5.28436179e-01 8.03273423e-01 1.93146344e-01
  7.96285779e-01 4.66358390e-01 4.23241345e-02 7.79289870e-01
  5.37701356e-01 2.11296125e-01 1.10978913e-01 1.70946366e-01
  5.99920053e-01 4.97519438e-01 8.92420217e-01 6.17585394e-01
  8.33395818e-01 4.55960249e-01 5.83019495e-01 3.87556489e-01]
 [1.54636899e-01 6.01803167e-01 6.88269055e-01 3.07780848e-01
  5.86286872e-01 3.16307646e-01 6.25100073e-01 2.03218676e-01
  1.64132265e-01 3.77665958e-02 7.35521072e-02 1.99397969e-01
  2.51233437e-01 1.07114630e-01 7.77217775e-01 3.34398848e-01
  9.84492217e-01 7.06132862e-01 4.05259049e-04 7.24624659e-01]
 [6.85194455e-01 8.70056270e-01 3.15734408e-01 3.43172708e-01
  1.72546157e-01 8.44240826e-01 4.57776612e-01 8.31182010e-01
  1.84717128e-02 5.45528833e-01 1.46779555e-01 7.82748887e-01
  7.44976472e-01 1.82727532e-01 5.68065243e-01 5.46627120e-01
  8.53321318e-01 7.84926232e-01 1.89166455e-01 4.61437875e-01]])

In [48]:
a[3:5]

GridArray(noname : [[ 9.52798582 43.4973796   9.34051829  6.89698967  5.99668414]
 [ 8.37992184  7.58680271 23.85570971  8.27163313  6.21833324]])

In [52]:
np.sum(a, axis=0)

GridArray(noname : [256.35961124 288.31803594 377.4480668  205.9102254  363.36298254])

In [54]:
a * 2

GridArray(noname : [[45.47811478 45.706479    0.52845548 42.12316125 14.2766544 ]
 [11.25904402 11.77017832 79.70579063 86.53393305 92.16097635]
 [14.20611154 13.87158392 78.48376504  0.93997064 19.88195884]
 [19.05597164 86.99475919 18.68103659 13.79397933 11.99336827]
 [16.75984368 15.17360543 47.71141942 16.54326626 12.43666647]
 [65.21116424 22.19768134 15.70783322 15.89429074 16.41839842]
 [15.53873813 96.26061262 13.53151367 19.16121652 66.00694125]
 [40.03123255 14.77953077 45.29566493 70.67184211 68.34401182]
 [93.63028731  0.74711847 14.97870028 10.06730778 17.19575213]
 [10.42539435 11.57627994 18.9562908  18.98394774 55.76341815]
 [ 0.9704821  18.63989469 30.72068634 14.76564748 39.60688172]
 [18.55220009 14.84798858 70.31710629 11.22818099 15.97927864]
 [15.91020629  0.60473726 82.87437699 18.49549445 38.3789323 ]
 [29.68042017 13.36815733 15.397396   12.07440607 14.81297628]
 [19.29783481 15.93135102 21.73173143 13.55329291 19.02303471]
 [13.07343232 13.25273764 46.39977999 17.68788222 19.95362998]
 [10.72137865 59.95912198 12.63757904  0.83001963 89.42893959]
 [14.0347887   0.25018907 14.05504142 17.04126729 64.77579693]
 [16.94648697 52.79636609 73.24401862  0.7501324  18.62083887]
 [41.93609013 67.9076992  53.93794742 10.68121193 31.66750996]])

In [55]:
m = np.ma.masked_array(np.arange(10))

In [56]:
m.mask = m < 6

In [57]:
(m * 3).data

array([ 0,  1,  2,  3,  4,  5, 18, 21, 24, 27])

In [58]:
# add something
g['a'] = np.random.rand(g.grid.size).reshape(g.shape)

TypeError: data type not understood

In [100]:
np.asanyarray(g['a'])

array(GridData(Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)
[]), dtype=object)

In [32]:
g

GridData(Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)
[GridArray(a : [[0.92923727 0.66677596 0.23727435 0.1610907  0.01653312]
 [0.55190353 0.27774722 0.29892989 0.93888069 0.85850405]
 [0.73551706 0.35244653 0.8760508  0.21956474 0.53441049]
 [0.15723997 0.08435455 0.88621504 0.04831482 0.71454138]
 [0.85049881 0.99898884 0.52455096 0.7870131  0.69769233]
 [0.55569202 0.47328259 0.70182388 0.97605759 0.97067788]
 [0.35147541 0.53804803 0.42583771 0.34038949 0.67097437]
 [0.99991814 0.40016164 0.9862341  0.22136795 0.00428525]
 [0.1870811  0.55282106 0.89642015 0.02093399 0.89793334]
 [0.32208858 0.86061124 0.16765693 0.39742282 0.26526869]
 [0.55569622 0.82761335 0.09299961 0.60893835 0.49450812]
 [0.35534096 0.54596017 0.43240258 0.9995946  0.32889435]
 [0.9596192  0.34237546 0.67684045 0.36497417 0.14907469]
 [0.33104808 0.03411093 0.13289779 0.8052429  0.65576376]
 [0.66148267 0.397798   0.65264809 0.14355531 0.58967196]
 [0.22599018 0.5112301  0.55603438 0.66878642 0.75357486]
 [0.97331045 0.6453644  0.74637954 0.34437067 0.37256701]
 [0.55422566 0.43232625 0.94590443 0.28158927 0.98584402]
 [0.76719059 0.269261   0.28188932 0.52344498 0.06515638]
 [0.25834844 0.93810894 0.97695424 0.33338629 0.58261418]]), GridArray(b : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]])])

In [33]:
g['b'] = np.ones(g.shape)

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 b [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
finalize


In [34]:
g.shape

(20, 5)

In [35]:
g['b'].T

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 b b : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
finalize
new  <class 'pynocular.griddata.GridArray'> (points) [0 1 2 3 4]
(edges)  None
(nbins)  5
(points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5

GridArray(b : b : [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]])

In [42]:
np.sin(a).grid

ufunc
() {}


Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)

In [43]:
a = g['a']

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 a a : [[0.92923727 0.66677596 0.23727435 0.1610907  0.01653312]
 [0.55190353 0.27774722 0.29892989 0.93888069 0.85850405]
 [0.73551706 0.35244653 0.8760508  0.21956474 0.53441049]
 [0.15723997 0.08435455 0.88621504 0.04831482 0.71454138]
 [0.85049881 0.99898884 0.52455096 0.7870131  0.69769233]
 [0.55569202 0.47328259 0.70182388 0.97605759 0.97067788]
 [0.35147541 0.53804803 0.42583771 0.34038949 0.67097437]
 [0.99991814 0.40016164 0.9862341  0.22136795 0.00428525]
 [0.1870811  0.55282106 0.89642015 0.02093399 0.89793334]
 [0.32208858 0.86061124 0.167

In [48]:
a.view(np.ndarray)

[autoreload of pynocular.griddata failed: Traceback (most recent call last):
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    update_generic(old_obj, new_obj)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 289, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 265, in update_function
    setattr(old, name, getattr(new, na

array([Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
       Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5)], dtype=object)

In [ ]:
g['b'][g['a'] < 0.5] *= -1

In [ ]:
g

In [ ]:
g['a']

In [ ]:
np.sum(g['a'], axis='y')

In [ ]:
g[:,-2]

In [ ]:
g[::-1, ::-1]

In [ ]:
g[[0,3,5], 2:-1]

In [ ]:
g[0,0]

In [ ]:
g.grid.edges[0].max()

In [ ]:
np.mean(g['b'], axis='x') + np.std(g['a'], axis='x')

In [ ]:
g['c'] = np.sqrt(g['x']) * np.sqrt(g['y'])

In [ ]:
g.plot('c', cbar=True)

In [ ]:
g['m'] = np.arange(g.grid.size * 3).reshape(g.shape + (-1,))

In [ ]:
g.plot('m') #it's interpreted as an RGB image, since the excess dimension is 3

In [ ]:
g['m'][:,:,0]

In [ ]:
g[:,3]

In [ ]:
g['m']

In [ ]:
g.T[:,3:5]['m']

In [ ]:
np.sum(g)

In [ ]:
np.sum(g, axis=(0))

# Stuff to fix

In [ ]:
np.sum(g['m'], axis=(0,1))

In [ ]:
# because of this
np.sum(g['m'], axis=-1).grid

In [ ]:
np.sum(g['m'], axis=-1)

In [ ]:
1 - 3 * g['a']

In [ ]:
2 ** g['a']

In [ ]:
g['a']

In [ ]:
g['a']

In [ ]:
a = g['a']

In [ ]:
a.T

In [ ]:
np.mean(a, axis='x')

In [ ]:
a

In [ ]:
from scipy import ndimage

In [ ]:
ndimage.gaussian_filter(a, sigma=1)

In [ ]:
np.median(a)

In [ ]:
np.cumsum(a)

In [ ]:
a.dtype

In [ ]:
np.sin(a)

In [ ]:
np.dot(a,a.T)

In [ ]:
b = a.values

In [ ]:
np.dot(b,b.T)

In [19]:
l = range(3)

In [20]:
l.next()

AttributeError: 'range' object has no attribute 'next'