In [1]:
%reload_ext autoreload
%autoreload 2
import numpy as np
import pynocular as pn
from matplotlib import pyplot as plt
from uncertainties import unumpy

In [2]:
g2d = pn.Grid(x=np.arange(10), y=np.arange(20))

In [3]:
b = pn.GridArray(np.random.rand(g2d.size).reshape(g2d.shape), grid=g2d)

In [4]:
f = np.sum(np.cos(b) -1.2 / b, axis='y')

In [5]:
f[f>-50] *= 33

In [6]:
f[0:2] *= 0

In [7]:
a = pn.GridArray(np.arange(10), x=10)

In [8]:
a[[2,7]] *= 0

In [9]:
a.grid

Grid(
Axis("x",
points = None,
edges = edges: None)
nbins = 10),)

In [10]:
f[3] *= 4

In [11]:
f[3]

-2382.882995365431

In [12]:
f

GridArray(noname : [-0.0 -0.0 -474.3121145787575 -2382.882995365431 -254.1258283850167
 -63.571481139331304 -1264.3758724175887 -206.29775885700397
 -101.32515261963582 -172.85859385977105])

In [13]:
np.cumsum(f, axis='x')

array([   -0.        ,    -0.        ,  -474.31211458, -2857.19510994,
       -3111.32093833, -3174.89241947, -4439.26829189, -4645.56605074,
       -4746.89120336, -4919.74979722])

In [14]:
f

GridArray(noname : [-0.0 -0.0 -474.3121145787575 -2382.882995365431 -254.1258283850167
 -63.571481139331304 -1264.3758724175887 -206.29775885700397
 -101.32515261963582 -172.85859385977105])

In [15]:
a = unumpy.uarray(np.arange(10), np.ones(10))

In [16]:
a = np.arange(10)

In [17]:
g = pn.Grid(x=np.arange(10))

In [18]:
u = pn.GridArray(a, grid=g)

In [19]:
u.grid

Grid(
Axis("x",
points = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
edges = edges: None)
nbins = 10),)

In [20]:
np.max(u)

9

In [21]:
np.amax(np.empty_like(u))

9

In [22]:
u.T

GridArray(noname : [0 1 2 3 4 5 6 7 8 9])

In [25]:
unumpy.cos(u)

GridArray(noname : [1.0 0.5403023058681398 -0.4161468365471424 -0.9899924966004454
 -0.6536436208636119 0.28366218546322625 0.960170286650366
 0.7539022543433046 -0.14550003380861354 -0.9111302618846769])

In [26]:
np.ones_like(u)

GridArray(noname : [1 1 1 1 1 1 1 1 1 1])

In [27]:
np.sqrt(u)

GridArray(noname : [0.0 1.0 1.4142135623730951 1.7320508075688772 2.0 2.23606797749979
 2.449489742783178 2.6457513110645907 2.8284271247461903 3.0])

In [28]:
np.asarray(10 / u)

array([10.        , 10.        ,  5.        ,  3.33333333,  2.5       ,
        2.        ,  1.66666667,  1.42857143,  1.25      ,  1.11111111])

In [29]:
u

GridArray(noname : [0 1 2 3 4 5 6 7 8 9])

In [30]:
np.sqrt(u[u>2])

GridArray(noname : [-- -- -- 1.7320508075688772 2.0 2.23606797749979 2.449489742783178
 2.6457513110645907 2.8284271247461903 3.0])

In [31]:
u[0:3]

GridArray(noname : [0 1 2])

In [32]:
g = pn.GridData(x=np.arange(20), y=np.arange(5))
#g = pn.GridData(y=np.arange(5))

In [33]:
g.grid['x'].edges = pn.edges(points=g.grid['x'].points)

In [34]:
e = pn.edges(points=np.arange(11))

In [35]:
e[0,0]

-0.5

In [36]:
a = pn.GridArray(np.random.rand(g.grid.size).reshape(g.shape), grid=g.grid)

In [37]:
a.astype(np.int)

GridArray(noname : [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]])

In [38]:
np.ones_like(a)

GridArray(noname : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]])

In [39]:
np.all(np.abs(-a) == a)

True

In [40]:
np.abs(-a)

GridArray(noname : [[0.6090512179362731 0.24240315060303652 0.82475069507919
  0.04721557487620287 0.47020945913887724]
 [0.9477584407392804 0.9304074769454445 0.3128550553690391
  0.5742226500018888 0.46141825406130976]
 [0.653176016163993 0.7969671797141749 0.14710621213107034
  0.8726627938228955 0.4738259032098747]
 [0.9299228137042121 0.0641047407843216 0.06439484846420418
  0.8678475486421867 0.5429523207564606]
 [0.7771980020783721 0.7374470142281471 0.2499881957529445
  0.9270147164288076 0.7054490109210276]
 [0.4548299277478739 0.12486041807215775 0.9312116880045289
  0.39568159726007057 0.7355185938427693]
 [0.9969558772687921 0.8484670258530699 0.6295197181128965
  0.5719979228660432 0.03388313693910039]
 [0.44141307674717845 0.15051589070492877 0.9080341594125297
  0.9626157300297237 0.8450917353707427]
 [0.1422219395683666 0.9994504809337902 0.5203747408940989
  0.537948795369295 0.8042032311065676]
 [0.6376644721087648 0.8705119966302779 0.20820389427065822
  0.49429364474300563 0.5779686892422542]
 [0.7964107323680851 0.41769891459888586 0.9433863600921516
  0.05400660388129952 0.7561204452526614]
 [0.26680638665748324 0.6173869566793575 0.5543929342139682
  0.8330807822470166 0.9769338982476143]
 [0.8566739643904101 0.8624382631101342 0.8588723807029602
  0.3445894465986914 0.9202204631905412]
 [0.8236337882126546 0.2050825424749939 0.7049032140397264
  0.07860413884219164 0.5784354290390797]
 [0.7079131299171442 0.6417313680947817 0.4582405549737313
  0.18240846204747174 0.9510777920927976]
 [0.7242910991705488 0.26896543972776155 0.30446311215924227
  0.7573978476284442 0.6465085120803139]
 [0.3825225829997555 0.16899325162990575 0.6004275238259735
  0.6979692759823675 0.8295610464869436]
 [0.7402737156159738 0.24665665241372436 0.31709333285746144
  0.6521965426702042 0.4885038069697989]
 [0.597704530814728 0.7551676922107817 0.5644224907095825
  0.3232984219617878 0.6592219271141241]
 [0.97099300639683 0.46620780847874843 0.30960835820924215
  0.46585694075065087 0.9992808577072293]])

In [41]:
np.sum(a, axis='y')

GridArray(noname : [2.1936301  3.22666188 2.94373811 2.46922227 3.39709694 2.64210222
 3.08082368 3.30767059 3.00419919 2.7886427  2.96762306 3.24860096
 3.84279452 2.39065911 2.94137131 2.70162601 2.67947368 2.44472405
 2.89981506 3.21194697])

In [42]:
a

GridArray(noname : [[0.60905122 0.24240315 0.8247507  0.04721557 0.47020946]
 [0.94775844 0.93040748 0.31285506 0.57422265 0.46141825]
 [0.65317602 0.79696718 0.14710621 0.87266279 0.4738259 ]
 [0.92992281 0.06410474 0.06439485 0.86784755 0.54295232]
 [0.777198   0.73744701 0.2499882  0.92701472 0.70544901]
 [0.45482993 0.12486042 0.93121169 0.3956816  0.73551859]
 [0.99695588 0.84846703 0.62951972 0.57199792 0.03388314]
 [0.44141308 0.15051589 0.90803416 0.96261573 0.84509174]
 [0.14222194 0.99945048 0.52037474 0.5379488  0.80420323]
 [0.63766447 0.870512   0.20820389 0.49429364 0.57796869]
 [0.79641073 0.41769891 0.94338636 0.0540066  0.75612045]
 [0.26680639 0.61738696 0.55439293 0.83308078 0.9769339 ]
 [0.85667396 0.86243826 0.85887238 0.34458945 0.92022046]
 [0.82363379 0.20508254 0.70490321 0.07860414 0.57843543]
 [0.70791313 0.64173137 0.45824055 0.18240846 0.95107779]
 [0.7242911  0.26896544 0.30446311 0.75739785 0.64650851]
 [0.38252258 0.16899325 0.60042752 0.69796928 0.82956105]
 [0.74027372 0.24665665 0.31709333 0.65219654 0.48850381]
 [0.59770453 0.75516769 0.56442249 0.32329842 0.65922193]
 [0.97099301 0.46620781 0.30960836 0.46585694 0.99928086]])

In [43]:
np.log10(np.exp(np.fabs(a)))

GridArray(noname : [[0.2645075831461783 0.10527435070286165 0.3581846758187636
  0.020505463628624744 0.20420937344272694]
 [0.4116062609902996 0.40407083315893355 0.13587122418231004
  0.24938172827968258 0.20039140158825955]
 [0.2836707395315714 0.3461184484078634 0.06388741618221307
  0.3789926359195587 0.20577997514687285]
 [0.403860346587685 0.027840335186469237 0.02796632735099993
  0.37690140150856555 0.2358011968410952]
 [0.33753280364886906 0.32026916897531316 0.10856849395645377
  0.4025973759881389 0.30637261270710914]
 [0.19753012782535634 0.0542261905768712 0.40442009758417946
  0.17184233428071352 0.3194316666431538]
 [0.43297243619885195 0.368484547404852 0.27339693982572155
  0.24841554156084444 0.014715259402223525]
 [0.19170326347123623 0.06536822077190355 0.39435422481251936
  0.4180586997451794 0.36701867737355665]
 [0.061766203560119325 0.4340558288050963 0.22599587849214156
  0.23362819337538637 0.3492610255983479]
 [0.27693416154258654 0.37805855656711185 0.09042180239251492
  0.21466900235173364 0.25100861245076633]
 [0.34587678639598685 0.1814043337072738 0.40970749049081556
  0.023454770051983147 0.3283789370274607]
 [0.11587254146189037 0.26812774848488696 0.24076979213527883
  0.36180238670952386 0.4242770011931718]
 [0.372048775524938 0.3745521786509561 0.37300353559840455
  0.14965329517990697 0.3996466692981065]
 [0.3576996093298275 0.0890662165315791 0.30613557613332
  0.03413734375392089 0.25121131496901233]
 [0.30744276598987547 0.2787003920277882 0.1990113444093752
  0.07921898851967571 0.4130478369666302]
 [0.31455562766141026 0.1168102062964485 0.13222664955384975
  0.3289337058304332 0.28077507929996215]
 [0.16612744700017248 0.07339283666175579 0.2607623603804536
  0.3031242050971501 0.36027378489116657]
 [0.32149678979003454 0.10712162306800888 0.13771188470830661
  0.2832453595980484 0.21215450775571493]
 [0.25957977954140854 0.3279651616387558 0.2451255731772611
  0.14040672066603352 0.28629644529529175]
 [0.4216969046447922 0.2024714786425285 0.13446120152139923
  0.2023190987243378 0.4339821623737983]])

In [44]:
np.cumsum(a, axis='y')

GridArray(noname : [[0.60905122 0.85145437 1.67620506 1.72342064 2.1936301 ]
 [0.94775844 1.87816592 2.19102097 2.76524362 3.22666188]
 [0.65317602 1.4501432  1.59724941 2.4699122  2.94373811]
 [0.92992281 0.99402755 1.0584224  1.92626995 2.46922227]
 [0.777198   1.51464502 1.76463321 2.69164793 3.39709694]
 [0.45482993 0.57969035 1.51090203 1.90658363 2.64210222]
 [0.99695588 1.8454229  2.47494262 3.04694054 3.08082368]
 [0.44141308 0.59192897 1.49996313 2.46257886 3.30767059]
 [0.14222194 1.14167242 1.66204716 2.19999596 3.00419919]
 [0.63766447 1.50817647 1.71638036 2.21067401 2.7886427 ]
 [0.79641073 1.21410965 2.15749601 2.21150261 2.96762306]
 [0.26680639 0.88419334 1.43858628 2.27166706 3.24860096]
 [0.85667396 1.71911223 2.57798461 2.92257405 3.84279452]
 [0.82363379 1.02871633 1.73361954 1.81222368 2.39065911]
 [0.70791313 1.3496445  1.80788505 1.99029352 2.94137131]
 [0.7242911  0.99325654 1.29771965 2.0551175  2.70162601]
 [0.38252258 0.55151583 1.15194336 1.84991263 2.67947368]
 [0.74027372 0.98693037 1.3040237  1.95622024 2.44472405]
 [0.59770453 1.35287222 1.91729471 2.24059314 2.89981506]
 [0.97099301 1.43720081 1.74680917 2.21266611 3.21194697]])

In [45]:
np.std(a, axis='y')[::-2]

GridArray(noname : [0.28576169332376233 0.18870825260398333 0.2104784673765963
 0.28810968923244035 0.24390392457573362 0.21486012730775267
 0.3145468829423186 0.2796520301939522 0.3745817448811843
 0.25383124469879254])

In [46]:
a[a > 0.5] *= 10

In [47]:
a.T

GridArray(noname : [[6.09051218 9.47758441 6.53176016 9.29922814 7.77198002 0.45482993
  9.96955877 0.44141308 0.14222194 6.37664472 7.96410732 0.26680639
  8.56673964 8.23633788 7.0791313  7.24291099 0.38252258 7.40273716
  5.97704531 9.70993006]
 [0.24240315 9.30407477 7.9696718  0.06410474 7.37447014 0.12486042
  8.48467026 0.15051589 9.99450481 8.70511997 0.41769891 6.17386957
  8.62438263 0.20508254 6.41731368 0.26896544 0.16899325 0.24665665
  7.55167692 0.46620781]
 [8.24750695 0.31285506 0.14710621 0.06439485 0.2499882  9.31211688
  6.29519718 9.08034159 5.20374741 0.20820389 9.4338636  5.54392934
  8.58872381 7.04903214 0.45824055 0.30446311 6.00427524 0.31709333
  5.64422491 0.30960836]
 [0.04721557 5.7422265  8.72662794 8.67847549 9.27014716 0.3956816
  5.71997923 9.6261573  5.37948795 0.49429364 0.0540066  8.33080782
  0.34458945 0.07860414 0.18240846 7.57397848 6.97969276 6.52196543
  0.32329842 0.46585694]
 [0.47020946 0.46141825 0.4738259  5.42952321 7.05449011 7.35518594
  0.03388314 8.45091735 8.04203231 5.77968689 7.56120445 9.76933898
  9.20220463 5.78435429 9.51077792 6.46508512 8.29561046 0.48850381
  6.59221927 9.99280858]])

In [48]:
a[3:5]

GridArray(noname : [[9.29922814 0.06410474 0.06439485 8.67847549 5.42952321]
 [7.77198002 7.37447014 0.2499882  9.27014716 7.05449011]])

In [49]:
np.sum(a, axis=0)

GridArray(noname : [119.38400198  82.95524335  82.77491262  84.93550089 117.21328008])

In [50]:
a * 2

GridArray(noname : [[12.18102436  0.4848063  16.4950139   0.09443115  0.94041892]
 [18.95516881 18.60814954  0.62571011 11.484453    0.92283651]
 [13.06352032 15.93934359  0.29421242 17.45325588  0.94765181]
 [18.59845627  0.12820948  0.1287897  17.35695097 10.85904642]
 [15.54396004 14.74894028  0.49997639 18.54029433 14.10898022]
 [ 0.90965986  0.24972084 18.62423376  0.79136319 14.71037188]
 [19.93911755 16.96934052 12.59039436 11.43995846  0.06776627]
 [ 0.88282615  0.30103178 18.16068319 19.2523146  16.90183471]
 [ 0.28444388 19.98900962 10.40749482 10.75897591 16.08406462]
 [12.75328944 17.41023993  0.41640779  0.98858729 11.55937378]
 [15.92821465  0.83539783 18.8677272   0.10801321 15.12240891]
 [ 0.53361277 12.34773913 11.08785868 16.66161564 19.53867796]
 [17.13347929 17.24876526 17.17744761  0.68917889 18.40440926]
 [16.47267576  0.41016508 14.09806428  0.15720828 11.56870858]
 [14.1582626  12.83462736  0.91648111  0.36481692 19.02155584]
 [14.48582198  0.53793088  0.60892622 15.14795695 12.93017024]
 [ 0.76504517  0.3379865  12.00855048 13.95938552 16.59122093]
 [14.80547431  0.4933133   0.63418667 13.04393085  0.97700761]
 [11.95409062 15.10335384 11.28844981  0.64659684 13.18443854]
 [19.41986013  0.93241562  0.61921672  0.93171388 19.98561715]])

In [51]:
m = np.ma.masked_array(np.arange(10))

In [52]:
m.mask = m < 6

In [53]:
(m * 3).data

array([ 0,  1,  2,  3,  4,  5, 18, 21, 24, 27])

In [54]:
# add something
g['a'] = np.random.rand(g.grid.size).reshape(g.shape)

In [55]:
np.asanyarray(g['a'])

GridArray(noname : [[0.51275065 0.88299932 0.88017659 0.36598017 0.02455188]
 [0.06501348 0.21005635 0.07974085 0.32626879 0.88743074]
 [0.64730109 0.56577588 0.94568822 0.98787972 0.20497248]
 [0.86558153 0.76482469 0.96981441 0.57919931 0.74509968]
 [0.21396473 0.55338587 0.03085662 0.34615434 0.05185877]
 [0.62885931 0.45797473 0.12953906 0.04337265 0.26549326]
 [0.26238439 0.47595952 0.31110059 0.93978747 0.33026101]
 [0.85246878 0.74168372 0.56833159 0.68584275 0.75407541]
 [0.56746781 0.80603049 0.60105486 0.85541385 0.25600805]
 [0.63978336 0.31314806 0.96449941 0.60595649 0.50522629]
 [0.55426776 0.54032913 0.96454664 0.36476766 0.93444188]
 [0.08264862 0.16418489 0.77073837 0.80689449 0.97806551]
 [0.17721213 0.08862304 0.29727216 0.96320464 0.60818777]
 [0.52281418 0.61216384 0.79331837 0.63728766 0.83838325]
 [0.6897116  0.22629358 0.2699679  0.88578814 0.16902952]
 [0.31092876 0.596973   0.44863035 0.50293539 0.17462122]
 [0.81107426 0.79782374 0.21306197 0.21938549 0.24801546]
 [0.8846168  0.16376923 0.92719051 0.08409564 0.28413598]
 [0.35655585 0.35820853 0.98025257 0.52941006 0.70963575]
 [0.08624143 0.29116432 0.41515673 0.26360781 0.48986161]])

In [58]:
g

GridData(Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)
{'a': masked_array(
  data=[[0.51275065, 0.88299932, 0.88017659, 0.36598017, 0.02455188],
        [0.06501348, 0.21005635, 0.07974085, 0.32626879, 0.88743074],
        [0.64730109, 0.56577588, 0.94568822, 0.98787972, 0.20497248],
        [0.86558153, 0.76482469, 0.96981441, 0.57919931, 0.74509968],
        [0.21396473, 0.55338587, 0.03085662, 0.34615434, 0.05185877],
        [0.62885931, 0.45797473, 0.12953906, 0.04337265, 0.26549326],
        [0.26238439, 0.47595952, 0.31110059, 0.93978747, 0.33026101],
        [0.85246878, 0.74168372, 0.56833159, 0.68584275, 0.75407541],
        [0.56746781, 0.80603049, 0.60105486, 0.85541385, 0.25600805],
        [0.63978336, 0.31314806, 0.96449941, 0.60595649, 0.50522629],
        [0.55426776, 0.54032913, 0.96454664, 0.36476766, 0.93444188],
        [0.08264862, 0.16418489, 0.77073837, 0.80689449, 0.97806551],
        [0.17721213, 0.08862304, 0.29727216, 0.96320464, 0.60818777],
        [0.52281418, 0.61216384, 0.79331837, 0.63728766, 0.83838325],
        [0.6897116 , 0.22629358, 0.2699679 , 0.88578814, 0.16902952],
        [0.31092876, 0.596973  , 0.44863035, 0.50293539, 0.17462122],
        [0.81107426, 0.79782374, 0.21306197, 0.21938549, 0.24801546],
        [0.8846168 , 0.16376923, 0.92719051, 0.08409564, 0.28413598],
        [0.35655585, 0.35820853, 0.98025257, 0.52941006, 0.70963575],
        [0.08624143, 0.29116432, 0.41515673, 0.26360781, 0.48986161]],
  mask=False,
  fill_value=1e+20)})

In [59]:
g['b'] = np.ones(g.shape)

In [60]:
g.shape

(20, 5)

In [61]:
g['b'].T

GridArray(noname : [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]])

In [42]:
np.sin(a).grid

ufunc
() {}


Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)

In [43]:
a = g['a']

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 a a : [[0.92923727 0.66677596 0.23727435 0.1610907  0.01653312]
 [0.55190353 0.27774722 0.29892989 0.93888069 0.85850405]
 [0.73551706 0.35244653 0.8760508  0.21956474 0.53441049]
 [0.15723997 0.08435455 0.88621504 0.04831482 0.71454138]
 [0.85049881 0.99898884 0.52455096 0.7870131  0.69769233]
 [0.55569202 0.47328259 0.70182388 0.97605759 0.97067788]
 [0.35147541 0.53804803 0.42583771 0.34038949 0.67097437]
 [0.99991814 0.40016164 0.9862341  0.22136795 0.00428525]
 [0.1870811  0.55282106 0.89642015 0.02093399 0.89793334]
 [0.32208858 0.86061124 0.167

In [48]:
a.view(np.ndarray)

[autoreload of pynocular.griddata failed: Traceback (most recent call last):
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    update_generic(old_obj, new_obj)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 289, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 265, in update_function
    setattr(old, name, getattr(new, na

array([Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
       Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5)], dtype=object)

In [ ]:
g['b'][g['a'] < 0.5] *= -1

In [ ]:
g

In [ ]:
g['a']

In [ ]:
np.sum(g['a'], axis='y')

In [ ]:
g[:,-2]

In [ ]:
g[::-1, ::-1]

In [ ]:
g[[0,3,5], 2:-1]

In [ ]:
g[0,0]

In [ ]:
g.grid.edges[0].max()

In [ ]:
np.mean(g['b'], axis='x') + np.std(g['a'], axis='x')

In [ ]:
g['c'] = np.sqrt(g['x']) * np.sqrt(g['y'])

In [ ]:
g.plot('c', cbar=True)

In [ ]:
g['m'] = np.arange(g.grid.size * 3).reshape(g.shape + (-1,))

In [ ]:
g.plot('m') #it's interpreted as an RGB image, since the excess dimension is 3

In [ ]:
g['m'][:,:,0]

In [ ]:
g[:,3]

In [ ]:
g['m']

In [ ]:
g.T[:,3:5]['m']

In [ ]:
np.sum(g)

In [ ]:
np.sum(g, axis=(0))

# Stuff to fix

In [ ]:
np.sum(g['m'], axis=(0,1))

In [ ]:
# because of this
np.sum(g['m'], axis=-1).grid

In [ ]:
np.sum(g['m'], axis=-1)

In [ ]:
1 - 3 * g['a']

In [ ]:
2 ** g['a']

In [ ]:
g['a']

In [ ]:
g['a']

In [ ]:
a = g['a']

In [ ]:
a.T

In [ ]:
np.mean(a, axis='x')

In [ ]:
a

In [ ]:
from scipy import ndimage

In [ ]:
ndimage.gaussian_filter(a, sigma=1)

In [ ]:
np.median(a)

In [ ]:
np.cumsum(a)

In [ ]:
a.dtype

In [ ]:
np.sin(a)

In [ ]:
np.dot(a,a.T)

In [ ]:
b = a.values

In [ ]:
np.dot(b,b.T)

In [19]:
l = range(3)

In [20]:
l.next()

AttributeError: 'range' object has no attribute 'next'

In [128]:
from collections import OrderedDict

In [131]:
o = OrderedDict(a=12, b=23)

In [134]:
len(o)

2

In [140]:
for i in o.values():
    print(i)

12
23


In [141]:
o.keys()

odict_keys(['a', 'b'])

In [145]:
o.get()

<function OrderedDict.get(key, default=None, /)>

In [144]:
o.

OrderedDict()