In [1]:
%reload_ext autoreload
%autoreload 2
import numpy as np
import pynocular as pn
from matplotlib import pyplot as plt

In [2]:
g = pn.GridData(x=np.arange(20), y=np.arange(5))
#g = pn.GridData(y=np.arange(5))

In [3]:
g.grid['x'].edges = pn.edges(points=g.grid['x'].points)

In [4]:
e = pn.edges(points=np.arange(11))

In [5]:
e[0,0]

-0.5

In [6]:
g

GridData(Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)
[])

In [7]:
# add something
g['a'] = np.random.rand(g.grid.size).reshape(g.shape)

In [8]:
g

GridData(Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)
[GridArray(a : [[0.42650651 0.08841262 0.65603125 0.90193056 0.60435964]
 [0.84928844 0.66927707 0.95396353 0.3403454  0.92569702]
 [0.42305686 0.17199805 0.42836883 0.96733786 0.80113828]
 [0.00756194 0.75777209 0.28758397 0.27176994 0.92312798]
 [0.23948777 0.38301604 0.58950698 0.37635754 0.31654917]
 [0.39586844 0.55990162 0.00803872 0.96303506 0.04574157]
 [0.14531024 0.02163611 0.73264906 0.1345545  0.97605709]
 [0.44945697 0.39283611 0.94880498 0.59439472 0.43005778]
 [0.70080324 0.36544196 0.76767331 0.09619144 0.67262229]
 [0.59730257 0.79893815 0.53978705 0.23627267 0.40071414]
 [0.12960167 0.98564403 0.62250388 0.41362403 0.19445148]
 [0.88009964 0.44441822 0.81071197 0.71618141 0.7294633 ]
 [0.41824145 0.7327171  0.09872942 0.03401247 0.25443439]
 [0.09600545 0.53762401 0.44305801 0.80283179 0.46607574]
 [0.79491016 0.15660884 0.33508485 0.77371216 0.55365169]
 [0.78948858 0.65983809 0.43994384 0.00420234 0.35209699]
 [0.84919673 0.32108528 0.56465983 0.36003323 0.39075924]
 [0.0936724  0.80386148 0.2399462  0.36600749 0.42027815]
 [0.48177859 0.3750921  0.59915905 0.88618276 0.80986706]
 [0.63423513 0.42533113 0.47120003 0.22267331 0.65880096]])])

In [9]:
g['b'] = np.ones(g.shape)

In [10]:
g.shape

(20, 5)

In [11]:
g['b'].T

GridArray(b : [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]])

In [13]:
g['b'][g['a'] < 0.5]

GridArray(b : [[1.0 1.0 -- -- --]
 [-- -- -- 1.0 --]
 [1.0 1.0 1.0 -- --]
 [1.0 -- 1.0 1.0 --]
 [1.0 1.0 -- 1.0 1.0]
 [1.0 -- 1.0 -- 1.0]
 [1.0 1.0 -- 1.0 --]
 [1.0 1.0 -- -- 1.0]
 [-- 1.0 -- 1.0 --]
 [-- -- -- 1.0 1.0]
 [1.0 -- -- 1.0 1.0]
 [-- 1.0 -- -- --]
 [1.0 -- 1.0 1.0 1.0]
 [1.0 -- 1.0 -- 1.0]
 [-- 1.0 1.0 -- --]
 [-- -- 1.0 1.0 1.0]
 [-- 1.0 -- 1.0 1.0]
 [1.0 -- 1.0 1.0 1.0]
 [1.0 1.0 -- -- --]
 [-- 1.0 1.0 1.0 --]])

In [20]:
g['b'][g['a'] < 0.5] *= -1

46


In [21]:
g['b']

GridArray(b : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]])

In [ ]:
np.sum(g['a'], axis='y')

In [ ]:
g[:,-2]

In [ ]:
g[::-1, ::-1]

In [ ]:
g[[0,3,5], 2:-1]

In [ ]:
g[0,0]

In [ ]:
g.grid.edges[0].max()

In [ ]:
np.mean(g['b'], axis='x') + np.std(g['a'], axis='x')

In [ ]:
g['c'] = np.sqrt(g['x']) * np.sqrt(g['y'])

In [ ]:
g.plot('c', cbar=True)

In [ ]:
g['m'] = np.arange(g.grid.size * 3).reshape(g.shape + (-1,))

In [ ]:
g.plot('m') #it's interpreted as an RGB image, since the excess dimension is 3

In [ ]:
g['m'][:,:,0]

In [ ]:
g[:,3]

In [ ]:
g['m']

In [ ]:
g.T[:,3:5]['m']

In [ ]:
np.sum(g)

In [ ]:
np.sum(g, axis=(0))

In [ ]:
n

# Stuff to fix

In [ ]:
np.sum(g['m'], axis=(0,1))

In [ ]:
# because of this
np.sum(g['m'], axis=-1).grid

In [ ]:
np.sum(g['m'], axis=-1)

In [ ]:
1 - 3 * g['a']

In [ ]:
2 ** g['a']

In [ ]:
g['a']

In [ ]:
2 ** 0.04