In [1]:
%reload_ext autoreload
%autoreload 2
import numpy as np
import pynocular as pn
from matplotlib import pyplot as plt
from uncertainties import unumpy

In [21]:
g2d = pn.Grid(x=np.arange(10), y=np.arange(20))

In [23]:
b = pn.GridArray(np.random.rand(g2d.size).reshape(g2d.shape), grid=g2d)

In [30]:
f = np.sum(np.cos(b) -1.2 / b, axis='y')

In [33]:
f[f>-50] *= 33

In [34]:
f

GridArray(noname : [-3232.4270070783373 -1468.1691593751518 -4638.6700603016
 -2732.4296529080843 -3527.501866527901 -1903.7874222247524
 -3165.163513825642 -1596.4224067958553 -252523.15086532937
 -3977.418218984074])

In [9]:
a = unumpy.uarray(np.arange(10), np.ones(10))

In [3]:
a = np.arange(10)

In [4]:
g = pn.Grid(x=np.arange(10))

In [10]:
u = pn.GridArray(a, grid=g)

In [11]:
u.grid

Grid(
Axis("x",
points = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
edges = edges: None)
nbins = 10),)

In [12]:
l = np.ones_like(u)

In [38]:
np.empty_like(u)

GridArray(noname : [None None None None None None None None None None])

In [13]:
u

GridArray(noname : [0.0+/-1.0 1.0+/-1.0 2.0+/-1.0 3.0+/-1.0 4.0+/-1.0 5.0+/-1.0 6.0+/-1.0
 7.0+/-1.0 8.0+/-1.0 9.0+/-1.0])

In [14]:
type(l)

pynocular.griddata.GridArray

In [15]:
l

GridArray(noname : [1 1 1 1 1 1 1 1 1 1])

In [19]:
unumpy.cos(u)

GridArray(noname : [1.0+/-0 0.5403023058681398+/-0.8414709848078965
 -0.4161468365471424+/-0.9092974268256817
 -0.9899924966004454+/-0.1411200080598672
 -0.6536436208636119+/-0.7568024953079282
 0.28366218546322625+/-0.9589242746631385
 0.960170286650366+/-0.27941549819892586
 0.7539022543433046+/-0.6569865987187891
 -0.14550003380861354+/-0.9893582466233818
 -0.9111302618846769+/-0.4121184852417566])

In [20]:
np.ones_like(u)

GridArray(noname : [1 1 1 1 1 1 1 1 1 1])

In [18]:
np.sqrt(u)

AttributeError: 'Variable' object has no attribute 'sqrt'

In [19]:
np.asarray(10 / u)

array([10.        , 10.        ,  5.        ,  3.33333333,  2.5       ,
        2.        ,  1.66666667,  1.42857143,  1.25      ,  1.11111111])

In [22]:
u

GridArray(noname : [0 1 2 3 4 5 6 7 8 9])

In [24]:
np.sqrt(u[u>2])

GridArray(noname : [-- -- -- 1.7320508075688772 2.0 2.23606797749979 2.449489742783178
 2.6457513110645907 2.8284271247461903 3.0])

In [32]:
u[0:3]

GridArray(noname : [0 1 2])

In [33]:
g = pn.GridData(x=np.arange(20), y=np.arange(5))
#g = pn.GridData(y=np.arange(5))

In [34]:
g.grid['x'].edges = pn.edges(points=g.grid['x'].points)

In [35]:
e = pn.edges(points=np.arange(11))

In [36]:
e[0,0]

-0.5

In [37]:
a = pn.GridArray(np.random.rand(g.grid.size).reshape(g.shape), grid=g.grid)

In [38]:
a.astype(np.int)

GridArray(noname : [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]])

In [39]:
np.ones_like(a)

GridArray(noname : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]])

In [40]:
np.all(np.abs(-a) == a)

True

In [41]:
np.abs(-a)

GridArray(noname : [[0.22739057390853723 0.22853239501782885 0.026422773822171508
  0.21061580624839826 0.7138327197653962]
 [0.5629522009102824 0.5885089158312274 0.39852895315606696
  0.43266966523444317 0.4608048817535497]
 [0.7103055771899627 0.6935791960757739 0.3924188251889823
  0.04699853176214552 0.9940979420924052]
 [0.9527985821600911 0.4349737959549047 0.9340518292831178
  0.6896989665414929 0.5996684137336417]
 [0.8379921842334166 0.7586802714481786 0.23855709708256778
  0.8271633129299253 0.062183332350118636]
 [0.3260558212216407 0.11098840671736265 0.7853916609601579
  0.7947145372496743 0.8209199209698094]
 [0.7769369063476846 0.48130306308095683 0.6765756836926766
  0.9580608259862058 0.33003470625647136]
 [0.20015616273085068 0.7389765386355732 0.2264783246537012
  0.35335921053869035 0.34172005908906466]
 [0.46815143653467706 0.03735592351964612 0.07489350138208051
  0.5033653892382303 0.8597876063181276]
 [0.5212697173773702 0.5788139970367367 0.9478145398571681
  0.09491973869701886 0.2788170907493698]
 [0.04852410506069649 0.9319947346581575 0.15360343170135538
  0.7382823738228709 0.19803440859222676]
 [0.9276100046279127 0.742399429202707 0.35158553146346927
  0.5614090497407499 0.07989639322209441]
 [0.7955103146460947 0.030236862991347868 0.41437188495630395
  0.9247747226574066 0.19189466147990808]
 [0.14840210086358074 0.6684078665881724 0.7698697998242188
  0.6037203032651353 0.7406488141144766]
 [0.9648917404492798 0.07965675511775538 0.10865865715308087
  0.6776646454902105 0.9511517354958947]
 [0.6536716161874087 0.6626368819048983 0.23199889994609857
  0.8843941112277738 0.9976814989864853]
 [0.5360689324931497 0.29979560989302323 0.6318789522292237
  0.04150098168646077 0.4471446979609369]
 [0.7017394349025021 0.012509453506931112 0.7027520711287638
  0.8520633646550284 0.3238789846458956]
 [0.8473243486167307 0.26398183047074564 0.3662200931094265
  0.03750661986742465 0.9310419435078767]
 [0.2096804506264297 0.33953849601705977 0.2696897370803203
  0.5340605966586015 0.15833754977978787]])

In [42]:
np.sum(a, axis='y')

GridArray(noname : [1.40679427 2.44346462 2.83740007 3.61119159 2.7245762  2.83807035
 3.22291119 1.8606903  1.94355386 2.42163508 2.07043905 2.66290041
 2.35678845 2.93104888 2.78202353 3.43038301 1.95638917 2.59294331
 2.44607484 1.51130683])

In [43]:
np.std(a, axis='y')

GridArray(noname : [0.22923081746410676 0.07419374972851502 0.3224439160446376
 0.19830587254171572 0.328066750823367 0.29326538814055286
 0.22018646761993838 0.1932060562527066 0.30440150891731066
 0.2894773201944441 0.3525613999823639 0.29617071327951194
 0.34251904468969213 0.22641604444678307 0.39119201946425647
 0.2623789280329001 0.20624612021890848 0.3074715492242762
 0.34448557068051955 0.13074147737692673])

In [46]:
a[a > 0.5] *= 10

In [47]:
a

GridArray(noname : [[22.73905739 22.8532395   0.26422774 21.06158062  7.1383272 ]
 [ 5.62952201  5.88508916 39.85289532 43.26696652 46.08048818]
 [ 7.10305577  6.93579196 39.24188252  0.46998532  9.94097942]
 [ 9.52798582 43.4973796   9.34051829  6.89698967  5.99668414]
 [ 8.37992184  7.58680271 23.85570971  8.27163313  6.21833324]
 [32.60558212 11.09884067  7.85391661  7.94714537  8.20919921]
 [ 7.76936906 48.13030631  6.76575684  9.58060826 33.00347063]
 [20.01561627  7.38976539 22.64783247 35.33592105 34.17200591]
 [46.81514365  0.37355924  7.48935014  5.03365389  8.59787606]
 [ 5.21269717  5.78813997  9.4781454   9.49197387 27.88170907]
 [ 0.48524105  9.31994735 15.36034317  7.38282374 19.80344086]
 [ 9.27610005  7.42399429 35.15855315  5.6140905   7.98963932]
 [ 7.95510315  0.30236863 41.4371885   9.24774723 19.18946615]
 [14.84021009  6.68407867  7.698698    6.03720303  7.40648814]
 [ 9.6489174   7.96567551 10.86586572  6.77664645  9.51151735]
 [ 6.53671616  6.62636882 23.19988999  8.84394111  9.97681499]
 [ 5.36068932 29.97956099  6.31878952  0.41500982 44.7144698 ]
 [ 7.01739435  0.12509454  7.02752071  8.52063365 32.38789846]
 [ 8.47324349 26.39818305 36.62200931  0.3750662   9.31041944]
 [20.96804506 33.9538496  26.96897371  5.34060597 15.83375498]])

In [48]:
a[3:5]

GridArray(noname : [[ 9.52798582 43.4973796   9.34051829  6.89698967  5.99668414]
 [ 8.37992184  7.58680271 23.85570971  8.27163313  6.21833324]])

In [52]:
np.sum(a, axis=0)

GridArray(noname : [256.35961124 288.31803594 377.4480668  205.9102254  363.36298254])

In [54]:
a * 2

GridArray(noname : [[45.47811478 45.706479    0.52845548 42.12316125 14.2766544 ]
 [11.25904402 11.77017832 79.70579063 86.53393305 92.16097635]
 [14.20611154 13.87158392 78.48376504  0.93997064 19.88195884]
 [19.05597164 86.99475919 18.68103659 13.79397933 11.99336827]
 [16.75984368 15.17360543 47.71141942 16.54326626 12.43666647]
 [65.21116424 22.19768134 15.70783322 15.89429074 16.41839842]
 [15.53873813 96.26061262 13.53151367 19.16121652 66.00694125]
 [40.03123255 14.77953077 45.29566493 70.67184211 68.34401182]
 [93.63028731  0.74711847 14.97870028 10.06730778 17.19575213]
 [10.42539435 11.57627994 18.9562908  18.98394774 55.76341815]
 [ 0.9704821  18.63989469 30.72068634 14.76564748 39.60688172]
 [18.55220009 14.84798858 70.31710629 11.22818099 15.97927864]
 [15.91020629  0.60473726 82.87437699 18.49549445 38.3789323 ]
 [29.68042017 13.36815733 15.397396   12.07440607 14.81297628]
 [19.29783481 15.93135102 21.73173143 13.55329291 19.02303471]
 [13.07343232 13.25273764 46.39977999 17.68788222 19.95362998]
 [10.72137865 59.95912198 12.63757904  0.83001963 89.42893959]
 [14.0347887   0.25018907 14.05504142 17.04126729 64.77579693]
 [16.94648697 52.79636609 73.24401862  0.7501324  18.62083887]
 [41.93609013 67.9076992  53.93794742 10.68121193 31.66750996]])

In [55]:
m = np.ma.masked_array(np.arange(10))

In [56]:
m.mask = m < 6

In [57]:
(m * 3).data

array([ 0,  1,  2,  3,  4,  5, 18, 21, 24, 27])

In [58]:
# add something
g['a'] = np.random.rand(g.grid.size).reshape(g.shape)

TypeError: data type not understood

In [100]:
np.asanyarray(g['a'])

array(GridData(Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)
[]), dtype=object)

In [32]:
g

GridData(Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)
[GridArray(a : [[0.92923727 0.66677596 0.23727435 0.1610907  0.01653312]
 [0.55190353 0.27774722 0.29892989 0.93888069 0.85850405]
 [0.73551706 0.35244653 0.8760508  0.21956474 0.53441049]
 [0.15723997 0.08435455 0.88621504 0.04831482 0.71454138]
 [0.85049881 0.99898884 0.52455096 0.7870131  0.69769233]
 [0.55569202 0.47328259 0.70182388 0.97605759 0.97067788]
 [0.35147541 0.53804803 0.42583771 0.34038949 0.67097437]
 [0.99991814 0.40016164 0.9862341  0.22136795 0.00428525]
 [0.1870811  0.55282106 0.89642015 0.02093399 0.89793334]
 [0.32208858 0.86061124 0.16765693 0.39742282 0.26526869]
 [0.55569622 0.82761335 0.09299961 0.60893835 0.49450812]
 [0.35534096 0.54596017 0.43240258 0.9995946  0.32889435]
 [0.9596192  0.34237546 0.67684045 0.36497417 0.14907469]
 [0.33104808 0.03411093 0.13289779 0.8052429  0.65576376]
 [0.66148267 0.397798   0.65264809 0.14355531 0.58967196]
 [0.22599018 0.5112301  0.55603438 0.66878642 0.75357486]
 [0.97331045 0.6453644  0.74637954 0.34437067 0.37256701]
 [0.55422566 0.43232625 0.94590443 0.28158927 0.98584402]
 [0.76719059 0.269261   0.28188932 0.52344498 0.06515638]
 [0.25834844 0.93810894 0.97695424 0.33338629 0.58261418]]), GridArray(b : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]])])

In [33]:
g['b'] = np.ones(g.shape)

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 b [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
finalize


In [34]:
g.shape

(20, 5)

In [35]:
g['b'].T

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 b b : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
finalize
new  <class 'pynocular.griddata.GridArray'> (points) [0 1 2 3 4]
(edges)  None
(nbins)  5
(points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5

GridArray(b : b : [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]])

In [42]:
np.sin(a).grid

ufunc
() {}


Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)

In [43]:
a = g['a']

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 a a : [[0.92923727 0.66677596 0.23727435 0.1610907  0.01653312]
 [0.55190353 0.27774722 0.29892989 0.93888069 0.85850405]
 [0.73551706 0.35244653 0.8760508  0.21956474 0.53441049]
 [0.15723997 0.08435455 0.88621504 0.04831482 0.71454138]
 [0.85049881 0.99898884 0.52455096 0.7870131  0.69769233]
 [0.55569202 0.47328259 0.70182388 0.97605759 0.97067788]
 [0.35147541 0.53804803 0.42583771 0.34038949 0.67097437]
 [0.99991814 0.40016164 0.9862341  0.22136795 0.00428525]
 [0.1870811  0.55282106 0.89642015 0.02093399 0.89793334]
 [0.32208858 0.86061124 0.167

In [48]:
a.view(np.ndarray)

[autoreload of pynocular.griddata failed: Traceback (most recent call last):
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    update_generic(old_obj, new_obj)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 289, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 265, in update_function
    setattr(old, name, getattr(new, na

array([Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
       Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5)], dtype=object)

In [ ]:
g['b'][g['a'] < 0.5] *= -1

In [ ]:
g

In [ ]:
g['a']

In [ ]:
np.sum(g['a'], axis='y')

In [ ]:
g[:,-2]

In [ ]:
g[::-1, ::-1]

In [ ]:
g[[0,3,5], 2:-1]

In [ ]:
g[0,0]

In [ ]:
g.grid.edges[0].max()

In [ ]:
np.mean(g['b'], axis='x') + np.std(g['a'], axis='x')

In [ ]:
g['c'] = np.sqrt(g['x']) * np.sqrt(g['y'])

In [ ]:
g.plot('c', cbar=True)

In [ ]:
g['m'] = np.arange(g.grid.size * 3).reshape(g.shape + (-1,))

In [ ]:
g.plot('m') #it's interpreted as an RGB image, since the excess dimension is 3

In [ ]:
g['m'][:,:,0]

In [ ]:
g[:,3]

In [ ]:
g['m']

In [ ]:
g.T[:,3:5]['m']

In [ ]:
np.sum(g)

In [ ]:
np.sum(g, axis=(0))

# Stuff to fix

In [ ]:
np.sum(g['m'], axis=(0,1))

In [ ]:
# because of this
np.sum(g['m'], axis=-1).grid

In [ ]:
np.sum(g['m'], axis=-1)

In [ ]:
1 - 3 * g['a']

In [ ]:
2 ** g['a']

In [ ]:
g['a']

In [ ]:
g['a']

In [ ]:
a = g['a']

In [ ]:
a.T

In [ ]:
np.mean(a, axis='x')

In [ ]:
a

In [ ]:
from scipy import ndimage

In [ ]:
ndimage.gaussian_filter(a, sigma=1)

In [ ]:
np.median(a)

In [ ]:
np.cumsum(a)

In [ ]:
a.dtype

In [ ]:
np.sin(a)

In [ ]:
np.dot(a,a.T)

In [ ]:
b = a.values

In [ ]:
np.dot(b,b.T)

In [19]:
l = range(3)

In [20]:
l.next()

AttributeError: 'range' object has no attribute 'next'