In [1]:
%reload_ext autoreload
%autoreload 2
import numpy as np
import pynocular as pn
from matplotlib import pyplot as plt
from uncertainties import unumpy

In [2]:
a = unumpy.uarray(np.arange(10), np.ones(10))

In [3]:
a = np.arange(10)

In [4]:
g = pn.Grid(x=np.arange(10))

In [5]:
u = pn.GridArray(a, grid=g)

In [6]:
np.cos(u)

GridArray(noname : [1.0 0.5403023058681398 -0.4161468365471424 -0.9899924966004454
 -0.6536436208636119 0.28366218546322625 0.960170286650366
 0.7539022543433046 -0.14550003380861354 -0.9111302618846769])

In [7]:
np.sqrt(u)

GridArray(noname : [0.0 1.0 1.4142135623730951 1.7320508075688772 2.0 2.23606797749979
 2.449489742783178 2.6457513110645907 2.8284271247461903 3.0])

In [8]:
np.asarray(10 / u)

array([10.        , 10.        ,  5.        ,  3.33333333,  2.5       ,
        2.        ,  1.66666667,  1.42857143,  1.25      ,  1.11111111])

In [9]:
u**u

GridArray(noname : [        1         1         4        27       256      3125     46656
    823543  16777216 387420489])

In [10]:
c

NameError: name 'c' is not defined

In [11]:
g = pn.GridData(x=np.arange(20), y=np.arange(5))
#g = pn.GridData(y=np.arange(5))

In [12]:
g.grid['x'].edges = pn.edges(points=g.grid['x'].points)

In [13]:
e = pn.edges(points=np.arange(11))

In [14]:
e[0,0]

-0.5

In [15]:
a = pn.GridArray(np.random.rand(g.grid.size).reshape(g.shape), grid=g.grid)

In [16]:
a.astype(np.int)

GridArray(noname : [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]])

In [17]:
np.all(np.abs(-a) == a)

True

In [18]:
np.abs(-a)

GridArray(noname : [[0.8678661961141451 0.5727753064577465 0.9803521196830389
  0.9448188956525277 0.6118664939391859]
 [0.5733300990963746 0.6926553633671738 0.9899955408980734
  0.6406884550851085 0.17686227458600212]
 [0.937814298351445 0.6891157016534231 0.30815760990692564
  0.6938245471977024 0.2112048753247613]
 [0.993915838974534 0.5701303548174219 0.1303481084674446
  0.49806699798358045 0.1338794620324959]
 [0.3552485359383337 0.7196591129459916 0.9896483519439149
  0.5652572287439633 0.7398639143047728]
 [0.6826624908065779 0.12484618380539936 0.5986572132604333
  0.5707139243686726 0.20724774298703907]
 [0.9483879755130976 0.6515503472981253 0.11158100955773276
  0.38702898461820234 0.08363849041717886]
 [0.5186164719643436 0.33423375134741873 0.05621345116470655
  0.3277556877093196 0.8276208675037076]
 [0.04661464335167553 0.2470255066281919 0.24488555205150442
  0.9035193634824639 0.580236146478083]
 [0.5778786976854977 0.9789368368295888 0.2961544504791296
  0.1449864034273406 0.08368901461730793]
 [0.06540506460083817 0.05450190379970932 0.9761584811408579
  0.06055560810881333 0.18923006154049293]
 [0.4576607196004028 0.5238577106471293 0.13566181786701215
  0.24156180705778185 0.6867826884700308]
 [0.7145579491269544 0.8985887541350539 0.12716320019803762
  0.5486176058918856 0.1121677741660676]
 [0.48371724820695317 0.7809092377504654 0.0988788088619964
  0.8808220787238186 0.37624411188851603]
 [0.9799881319959356 0.657732187925681 0.5324583553100914
  0.8289677193096503 0.7490225888299702]
 [0.9736052567579919 0.22097376684187053 0.8785408000323938
  0.8542144690020332 0.9494378942748328]
 [0.6942344955623017 0.5252151926638656 0.20705407589694957
  0.20382050445423727 0.6000627694503113]
 [0.10286255903148678 0.7655483834773646 0.5072559986504374
  0.8705951628502481 0.7593650442520055]
 [0.2679673942698315 0.27900375014200285 0.9767921118085798
  0.7936625156252192 0.3861994717845153]
 [0.9071223726825723 0.34925664226047115 0.24491848627806534
  0.5552825654307563 0.5870962110837662]])

In [19]:
np.sum(a, axis='y')

TypeError: '<' not supported between instances of 'str' and 'int'

In [23]:
tuple((1,))

(1,)

In [10]:
np.std(a, axis='y')

finalize
new:  [0.14576225693594386 0.20939651614232307 0.26553891399792695
 0.23607027967622554 0.259821125642423 0.13411204087607995
 0.27580039774715953 0.18702244106961174 0.24579707099598153
 0.14111319011805135 0.2730187960097428 0.165470661954122
 0.22504554645441233 0.33279222050689367 0.1941271467464528
 0.19439195668272916 0.35403851750880727 0.2976253357868666
 0.28828634717395485 0.23382130506295062] () {}
finalize


GridArray(noname : [0.14576226 0.20939652 0.26553891 0.23607028 0.25982113 0.13411204
 0.2758004  0.18702244 0.24579707 0.14111319 0.2730188  0.16547066
 0.22504555 0.33279222 0.19412715 0.19439196 0.35403852 0.29762534
 0.28828635 0.23382131])

In [114]:
a[a < 0.5] *= 10

ufunc
<class 'numpy.ma.core.MaskedArray'>
finalize
new:  [[False False False  True False]
 [False False  True False  True]
 [False  True False False  True]
 [ True False  True False  True]
 [ True False False False False]
 [ True  True  True  True  True]
 [False  True  True  True False]
 [ True False False False False]
 [ True  True False  True  True]
 [False False False False False]
 [False  True False  True  True]
 [False False False  True  True]
 [ True  True False False False]
 [ True False  True  True False]
 [False  True  True  True False]
 [False False False  True False]
 [ True  True False False  True]
 [False  True  True False  True]
 [False  True False False False]
 [False  True False False False]] () {}
finalize
get masked
<class 'numpy.ma.core.MaskedArray'>
finalize
new:  [[0.6743389  0.71334815 0.55798581 0.3794698  0.97005524]
 [0.93827351 0.57985957 0.37606966 0.97158782 0.08743083]
 [0.82556196 0.28609943 0.74184402 0.754175   0.19636655]
 [0.32825098 0.66613843 0.36326

In [116]:
a

GridArray(noname : [[6.74338895 7.13348154 5.57985807 0.3794698  9.70055238]
 [9.3827351  5.79859569 0.37606966 9.7158782  0.08743083]
 [8.25561959 0.28609943 7.41844018 7.54175003 0.19636655]
 [0.32825098 6.66138433 0.36326925 6.0815281  0.19111882]
 [0.31523826 9.74795349 5.55311824 8.83168286 7.51887669]
 [0.47060935 0.36002629 0.3927608  0.06705039 0.31837585]
 [5.56043885 0.37992154 0.45843088 0.40549324 7.1881401 ]
 [0.02723426 9.56477672 8.16466003 9.22744211 9.93157076]
 [0.39067823 0.36996946 9.44464095 0.39372046 0.3129325 ]
 [8.20736528 9.11417562 9.86262104 8.59531666 9.91381891]
 [5.21340942 0.23417317 6.87758085 0.06963685 0.43495712]
 [7.51771703 8.43788568 5.53507753 0.35146925 0.02246337]
 [0.15243332 0.33434215 6.56711976 5.61272329 7.33356811]
 [0.4950176  9.08913498 0.30295529 0.03014041 7.27721684]
 [5.46528154 0.02373984 0.48735103 0.45984825 8.81998219]
 [7.49279761 8.28109902 5.96162978 0.01626028 5.16378486]
 [0.28256999 0.39230327 7.45158075 8.34175358 0.33478768]
 [8.43071438 0.49031524 0.32376543 7.39389555 0.48937093]
 [6.55565977 0.41298109 6.84505174 9.56278322 8.42050925]
 [9.36639702 0.2507017  7.31303284 5.53603484 8.52160534]])

In [38]:
a[3:5]

<class 'numpy.ma.core.MaskedArray'>
finalize
new:  [[ 0.17316328  0.35818986  0.07923509 11.56665951  0.1024713 ]
 [11.57720734 11.82604826  0.13436852 11.96924313 11.59499269]] () {}
finalize


GridArray(noname : [[ 0.17316328  0.35818986  0.07923509 11.56665951  0.1024713 ]
 [11.57720734 11.82604826  0.13436852 11.96924313 11.59499269]])

In [12]:
print(ma)

noname : [[0.7196396019918639 -- -- 0.621331755616624 0.5056894708855514]
 [0.6015274217245826 -- -- -- --]
 [0.6685276243123535 -- -- 0.8174657543483177 --]
 [-- 0.79508649155423 0.641067924372188 0.6169573451941059
  0.5256059704742136]
 [-- 0.7379783354252227 -- -- --]
 [-- -- -- -- --]
 [0.9382841865306513 -- -- -- 0.5661740288758051]
 [-- -- 0.6547735507434406 0.614576247172161 0.7577361817725057]
 [0.5022167628320954 0.9796139069812659 0.9717848017721806 --
  0.6962637728140734]
 [-- -- -- -- --]
 [-- 0.6624540629775398 0.5057565429647949 0.9278592163930885
  0.5557784781627689]
 [-- 0.8042658985735086 0.7055570171684586 0.7508012283205642 --]
 [0.6872241536380723 -- -- -- 0.6878781879539313]
 [0.8573017907140302 0.8354119461243761 -- 0.8154981576661366 --]
 [0.6059703833652312 -- 0.9750126902388006 0.6057489490753574
  0.8563044545382815]
 [-- 0.5173465972866244 0.5931991435612147 0.7108773195595761 --]
 [-- -- 0.7931170472462341 0.9344548349692149 0.9644610999968106]
 [-- -- --

In [79]:
(ma -1).data

finalize


array([[2.7196396 , 0.37715668, 0.33048003, 2.62133176, 2.50568947],
       [2.60152742, 0.15411598, 0.42218037, 0.01265511, 0.4069421 ],
       [2.66852762, 0.46253936, 0.04685216, 2.81746575, 0.35467804],
       [0.09574461, 2.79508649, 2.64106792, 2.61695735, 2.52560597],
       [0.13460241, 2.73797834, 0.01347162, 0.17159451, 0.0882253 ],
       [0.44385988, 0.19372214, 0.44398078, 0.10719023, 0.2881674 ],
       [2.93828419, 0.18667253, 0.46875801, 0.20252181, 2.56617403],
       [0.23614841, 0.41136651, 2.65477355, 2.61457625, 2.75773618],
       [2.50221676, 2.97961391, 2.9717848 , 0.36690206, 2.69626377],
       [0.21391107, 0.27309921, 0.48002566, 0.08211989, 0.11550164],
       [0.08598324, 2.66245406, 2.50575654, 2.92785922, 2.55577848],
       [0.38839345, 2.8042659 , 2.70555702, 2.75080123, 0.46219205],
       [2.68722415, 0.40330205, 0.07740489, 0.45086543, 2.68787819],
       [2.85730179, 2.83541195, 0.07017289, 2.81549816, 0.26888125],
       [2.60597038, 0.43402234, 2.

In [98]:
ma * ma

finalize


GridArray(noname : [[13.835718768706192 -- -- 13.11404368423738 12.289858666277816]
 [12.97099976943412 -- -- -- --]
 [13.45809493034284 -- -- 14.57304478562217 --]
 [-- 14.402681478377392 13.257375629891994 13.082380436953596
  12.42989745904342]
 [-- 13.97248203610832 -- -- --]
 [-- -- -- -- --]
 [15.510082333877394 -- -- -- 12.71759720422829]
 [-- -- 13.357369707213817 13.065161446621183 14.120581211802211]
 [12.265522253862121 15.837326848638694 15.77507451158848 --
  13.662365878217727]
 [-- -- -- -- --]
 [-- 13.413569763420691 12.290328938540469 15.428078023804128
  12.643560585765538]
 [-- 14.472439027049305 13.731152807486403 14.068509854371055 --]
 [13.595621959172 -- -- -- 13.60044552918637]
 [14.878777104645666 14.710384796473573 -- 14.558026191153685 --]
 [13.003022405707192 -- 15.800725887559508 13.001425483758043
  14.871084046091791]
 [-- 12.371727085443796 12.911080085289047 13.770610480821665 --]
 [-- -- 14.38773693410999 15.479934848412631 15.716951813387924]
 [-- -- -- 15.110885159333383 --]
 [-- 13.40925723734079 -- -- 15.16975333651568]
 [-- -- 14.604745556012974 -- 13.142604883801486]])

In [88]:
ma

GridArray(noname : [[3.719639601991864 -- -- 3.621331755616624 3.5056894708855513]
 [3.6015274217245827 -- -- -- --]
 [3.6685276243123535 -- -- 3.8174657543483175 --]
 [-- 3.7950864915542297 3.641067924372188 3.616957345194106
  3.5256059704742135]
 [-- 3.7379783354252227 -- -- --]
 [-- -- -- -- --]
 [3.9382841865306513 -- -- -- 3.566174028875805]
 [-- -- 3.6547735507434407 3.614576247172161 3.757736181772506]
 [3.5022167628320955 3.9796139069812657 3.9717848017721806 --
  3.6962637728140733]
 [-- -- -- -- --]
 [-- 3.66245406297754 3.5057565429647948 3.9278592163930885
  3.555778478162769]
 [-- 3.8042658985735085 3.7055570171684584 3.7508012283205643 --]
 [3.6872241536380725 -- -- -- 3.687878187953931]
 [3.8573017907140303 3.835411946124376 -- 3.815498157666137 --]
 [3.6059703833652312 -- 3.9750126902388008 3.605748949075357
  3.8563044545382814]
 [-- 3.5173465972866245 3.5931991435612147 3.710877319559576 --]
 [-- -- 3.793117047246234 3.9344548349692148 3.964461099996811]
 [-- -- -- 3.8872722003139146 --]
 [-- 3.66186526750245 -- -- 3.8948367535129993]
 [-- -- 3.8216155688416613 -- 3.6252730771352226]])

In [ ]:
np.ma.multiply

In [37]:
np.sum(a, axis=0)

finalize
new:  [8.623262685686472 4.708278282238981 8.023731424191265 7.095284779946406
 4.729493796603652] () {}
finalize


GridArray(noname : [8.62326269 4.70827828 8.02373142 7.09528478 4.7294938 ])

In [42]:
np.multiply(ma, 10)

ufunc
finalize
new:  [[8.979945347369082 -- 5.921580056391345 -- --]
 [-- -- 5.659395223376978 -- --]
 [7.556523623841022 -- 5.382173954126682 -- --]
 [5.674383632849526 -- 7.330904539825768 -- --]
 [5.8290103238138515 8.016418698576553 8.072699600076886
  7.293644721007078 --]
 [-- -- -- -- --]
 [7.122621942009818 -- -- 5.903258995841849 6.48668370913718]
 [6.153569919904903 -- 5.033586086343579 -- --]
 [-- -- 5.335819027893115 5.675499456111285 5.292038315573785]
 [-- -- 9.674599298247895 7.977543443300624 --]
 [-- -- -- 7.855717271389368 --]
 [-- -- 6.846004988293451 7.486193880308816 --]
 [6.159137729361131 -- 7.108436780476595 8.202056774760385 --]
 [9.022988014137075 6.01129976925632 6.7336868294752295 8.162881035079087
  8.454001039859747]
 [-- 8.486578933699265 -- -- --]
 [5.744333121221303 -- 7.138427857385122 7.252565849392452
  5.477200952404314]
 [8.324333892957606 9.899588649319227 -- -- 7.69192351610122]
 [9.720000547029143 7.118395801640239 -- -- 8.270320675056038]
 [-- 

GridArray(noname : [[8.97994535 4.2569477  5.92158006 1.18114332 0.75301406]
 [3.14762218 3.67836728 5.65939522 1.20688927 0.07652508]
 [7.55652362 1.6868849  5.38217395 2.39641268 1.72825098]
 [5.67438363 2.62847131 7.33090454 3.66920445 1.35767789]
 [5.82901032 8.0164187  8.0726996  7.29364472 0.7270028 ]
 [4.66066959 0.37824007 3.30735271 0.96435461 2.89198648]
 [7.12262194 0.70272785 3.97571908 5.903259   6.48668371]
 [6.15356992 4.06578042 5.03358609 2.1152375  2.42311199]
 [3.492752   1.36572099 5.33581903 5.67549946 5.29203832]
 [2.24873119 3.47260498 9.6745993  7.97754344 2.49378215]
 [0.62381026 2.41721426 1.97320955 7.85571727 1.56087993]
 [4.40978511 2.09004699 6.84600499 7.48619388 2.83856087]
 [6.15913773 2.57262418 7.10843678 8.20205677 3.79662364]
 [9.02298801 6.01129977 6.73368683 8.16288104 8.45400104]
 [3.52790047 8.48657893 3.58541007 1.64203614 4.3046915 ]
 [5.74433312 1.44987409 7.13842786 7.25256585 5.47720095]
 [8.32433389 9.89958865 2.87954493 1.30232047 7.69192352]
 [9.72000055 7.1183958  1.42497586 1.47085189 8.27032068]
 [2.54873874 0.40832111 3.72725499 2.22419384 3.53473153]
 [5.94577876 7.55050097 3.77545695 5.14348637 5.62276976]])

In [18]:
a * 2

finalize


AttributeError: 'NoneType' object has no attribute 'naxes'

GridArray(noname : [[1.79598907 0.42569477 1.18431601 0.11811433 0.07530141]
 [0.31476222 0.36783673 1.13187904 0.12068893 0.00765251]
 [1.51130472 0.16868849 1.07643479 0.23964127 0.1728251 ]
 [1.13487673 0.26284713 1.46618091 0.36692045 0.13576779]
 [1.16580206 1.60328374 1.61453992 1.45872894 0.07270028]
 [0.46606696 0.03782401 0.33073527 0.09643546 0.28919865]
 [1.42452439 0.07027279 0.39757191 1.1806518  1.29733674]
 [1.23071398 0.40657804 1.00671722 0.21152375 0.2423112 ]
 [0.3492752  0.1365721  1.06716381 1.13509989 1.05840766]
 [0.22487312 0.3472605  1.93491986 1.59550869 0.24937821]
 [0.06238103 0.24172143 0.19732096 1.57114345 0.15608799]
 [0.44097851 0.2090047  1.369201   1.49723878 0.28385609]
 [1.23182755 0.25726242 1.42168736 1.64041135 0.37966236]
 [1.8045976  1.20225995 1.34673737 1.63257621 1.69080021]
 [0.35279005 1.69731579 0.35854101 0.16420361 0.43046915]
 [1.14886662 0.14498741 1.42768557 1.45051317 1.09544019]
 [1.66486678 1.97991773 0.28795449 0.13023205 1.53838

In [21]:
m = np.ma.masked_array(np.arange(10))

In [43]:
m.mask = m < 6

In [99]:
(m * 3).data

NameError: name 'm' is not defined

In [16]:
# add something
g['a'] = np.random.rand(g.grid.size).reshape(g.shape)

TypeError: data type not understood

In [100]:
np.asanyarray(g['a'])

array(GridData(Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)
[]), dtype=object)

In [32]:
g

GridData(Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)
[GridArray(a : [[0.92923727 0.66677596 0.23727435 0.1610907  0.01653312]
 [0.55190353 0.27774722 0.29892989 0.93888069 0.85850405]
 [0.73551706 0.35244653 0.8760508  0.21956474 0.53441049]
 [0.15723997 0.08435455 0.88621504 0.04831482 0.71454138]
 [0.85049881 0.99898884 0.52455096 0.7870131  0.69769233]
 [0.55569202 0.47328259 0.70182388 0.97605759 0.97067788]
 [0.35147541 0.53804803 0.42583771 0.34038949 0.67097437]
 [0.99991814 0.40016164 0.9862341  0.22136795 0.00428525]
 [0.1870811  0.55282106 0.89642015 0.02093399 0.89793334]
 [0.32208858 0.86061124 0.16765693 0.39742282 0.26526869]
 [0.55569622 0.82761335 0.09299961 0.60893835 0.49450812]
 [0.35534096 0.54596017 0.43240258 0.9995946  0.32889435]
 [0.9596192  0.34237546 0.67684045 0.36497417 0.14907469]
 [0.33104808 0.03411093 0.13289779 0.8052429  0.65576376]
 [0.66148267 0.397798   0.65264809 0.14355531 0.58967196]
 [0.22599018 0.5112301  0.55603438 0.66878642 0.75357486]
 [0.97331045 0.6453644  0.74637954 0.34437067 0.37256701]
 [0.55422566 0.43232625 0.94590443 0.28158927 0.98584402]
 [0.76719059 0.269261   0.28188932 0.52344498 0.06515638]
 [0.25834844 0.93810894 0.97695424 0.33338629 0.58261418]]), GridArray(b : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]])])

In [33]:
g['b'] = np.ones(g.shape)

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 b [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
finalize


In [34]:
g.shape

(20, 5)

In [35]:
g['b'].T

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 b b : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
finalize
new  <class 'pynocular.griddata.GridArray'> (points) [0 1 2 3 4]
(edges)  None
(nbins)  5
(points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5

GridArray(b : b : [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]])

In [42]:
np.sin(a).grid

ufunc
() {}


Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)

In [43]:
a = g['a']

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 a a : [[0.92923727 0.66677596 0.23727435 0.1610907  0.01653312]
 [0.55190353 0.27774722 0.29892989 0.93888069 0.85850405]
 [0.73551706 0.35244653 0.8760508  0.21956474 0.53441049]
 [0.15723997 0.08435455 0.88621504 0.04831482 0.71454138]
 [0.85049881 0.99898884 0.52455096 0.7870131  0.69769233]
 [0.55569202 0.47328259 0.70182388 0.97605759 0.97067788]
 [0.35147541 0.53804803 0.42583771 0.34038949 0.67097437]
 [0.99991814 0.40016164 0.9862341  0.22136795 0.00428525]
 [0.1870811  0.55282106 0.89642015 0.02093399 0.89793334]
 [0.32208858 0.86061124 0.167

In [48]:
a.view(np.ndarray)

[autoreload of pynocular.griddata failed: Traceback (most recent call last):
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    update_generic(old_obj, new_obj)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 289, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 265, in update_function
    setattr(old, name, getattr(new, na

array([Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
       Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5)], dtype=object)

In [ ]:
g['b'][g['a'] < 0.5] *= -1

In [ ]:
g

In [ ]:
g['a']

In [ ]:
np.sum(g['a'], axis='y')

In [ ]:
g[:,-2]

In [ ]:
g[::-1, ::-1]

In [ ]:
g[[0,3,5], 2:-1]

In [ ]:
g[0,0]

In [ ]:
g.grid.edges[0].max()

In [ ]:
np.mean(g['b'], axis='x') + np.std(g['a'], axis='x')

In [ ]:
g['c'] = np.sqrt(g['x']) * np.sqrt(g['y'])

In [ ]:
g.plot('c', cbar=True)

In [ ]:
g['m'] = np.arange(g.grid.size * 3).reshape(g.shape + (-1,))

In [ ]:
g.plot('m') #it's interpreted as an RGB image, since the excess dimension is 3

In [ ]:
g['m'][:,:,0]

In [ ]:
g[:,3]

In [ ]:
g['m']

In [ ]:
g.T[:,3:5]['m']

In [ ]:
np.sum(g)

In [ ]:
np.sum(g, axis=(0))

# Stuff to fix

In [ ]:
np.sum(g['m'], axis=(0,1))

In [ ]:
# because of this
np.sum(g['m'], axis=-1).grid

In [ ]:
np.sum(g['m'], axis=-1)

In [ ]:
1 - 3 * g['a']

In [ ]:
2 ** g['a']

In [ ]:
g['a']

In [ ]:
g['a']

In [ ]:
a = g['a']

In [ ]:
a.T

In [ ]:
np.mean(a, axis='x')

In [ ]:
a

In [ ]:
from scipy import ndimage

In [ ]:
ndimage.gaussian_filter(a, sigma=1)

In [ ]:
np.median(a)

In [ ]:
np.cumsum(a)

In [ ]:
a.dtype

In [ ]:
np.sin(a)

In [ ]:
np.dot(a,a.T)

In [ ]:
b = a.values

In [ ]:
np.dot(b,b.T)

In [19]:
l = range(3)

In [20]:
l.next()

AttributeError: 'range' object has no attribute 'next'