In [1]:
%reload_ext autoreload
%autoreload 2
import numpy as np
import pynocular as pn
from matplotlib import pyplot as plt
from uncertainties import unumpy

In [2]:
g2d = pn.Grid(x=np.arange(10), y=np.arange(20))

In [3]:
b = pn.GridArray(np.random.rand(g2d.size).reshape(g2d.shape), grid=g2d)

In [4]:
f = np.sum(np.cos(b) -1.2 / b, axis='y')

In [5]:
f[f>-50] *= 33

In [8]:
f[0:2] *= 0

In [9]:
a = pn.GridArray(np.arange(10), x=10)

In [10]:
a[[2,7]] *= 0

In [11]:
a.grid

Grid(
Axis("x",
points = None,
edges = edges: None)
nbins = 10),)

In [12]:
f[3] *= 4

In [13]:
f[3]

-738.0734963094467

In [15]:
f

GridArray(noname : [-0.0 -0.0 -1470.6894488829053 -738.0734963094467 -127.49435628311903
 -74.22341324269432 -68.63467006385498 -99.94109076703614
 -161.07596748215147 -314.3714990857331])

In [16]:
np.cumsum(f, axis='x')

array([   -0.        ,    -0.        , -1470.68944888, -2208.76294519,
       -2336.25730148, -2410.48071472, -2479.11538478, -2579.05647555,
       -2740.13244303, -3054.50394212])

In [17]:
f

GridArray(noname : [-0.0 -0.0 -1470.6894488829053 -738.0734963094467 -127.49435628311903
 -74.22341324269432 -68.63467006385498 -99.94109076703614
 -161.07596748215147 -314.3714990857331])

In [18]:
a = unumpy.uarray(np.arange(10), np.ones(10))

In [19]:
a = np.arange(10)

In [20]:
g = pn.Grid(x=np.arange(10))

In [21]:
u = pn.GridArray(a, grid=g)

In [22]:
u.grid

Grid(
Axis("x",
points = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
edges = edges: None)
nbins = 10),)

In [23]:
np.max(u)

9

In [24]:
np.amax(np.empty_like(u))

9

In [25]:
u.T

GridArray(noname : [0 1 2 3 4 5 6 7 8 9])

In [26]:
type(l)

NameError: name 'l' is not defined

In [27]:
l

NameError: name 'l' is not defined

In [ ]:
unumpy.cos(u)

In [28]:
np.ones_like(u)

GridArray(noname : [1 1 1 1 1 1 1 1 1 1])

In [65]:
np.sqrt(u)

GridArray(noname : [0.0 1.0 1.4142135623730951 1.7320508075688772 2.0 2.23606797749979
 2.449489742783178 2.6457513110645907 2.8284271247461903 3.0])

In [66]:
np.asarray(10 / u)

array([10.        , 10.        ,  5.        ,  3.33333333,  2.5       ,
        2.        ,  1.66666667,  1.42857143,  1.25      ,  1.11111111])

In [67]:
u

GridArray(noname : [0 1 2 3 4 5 6 7 8 9])

In [68]:
np.sqrt(u[u>2])

GridArray(noname : [-- -- -- 1.7320508075688772 2.0 2.23606797749979 2.449489742783178
 2.6457513110645907 2.8284271247461903 3.0])

In [62]:
u[0:3]

GridArray(noname : [0 1 2])

In [109]:
g = pn.GridData(x=np.arange(20), y=np.arange(5))
#g = pn.GridData(y=np.arange(5))

In [110]:
g.grid['x'].edges = pn.edges(points=g.grid['x'].points)

In [111]:
e = pn.edges(points=np.arange(11))

In [112]:
e[0,0]

-0.5

In [113]:
a = pn.GridArray(np.random.rand(g.grid.size).reshape(g.shape), grid=g.grid)

In [122]:
a.astype(np.int)

GridArray(noname : [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]])

In [115]:
np.ones_like(a)

GridArray(noname : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]])

In [116]:
np.all(np.abs(-a) == a)

True

In [117]:
np.abs(-a)

GridArray(noname : [[0.9402906749411682 0.7920199731661808 0.7496966922497037
  0.5852068344674549 0.48946347081804253]
 [0.0772316164594764 0.8631533279009991 0.07257648694686036
  0.2988893555269666 0.060144230129755005]
 [0.9559651825994855 0.2890394920074668 0.7178726136064401
  0.5650625093371312 0.5105078558754774]
 [0.07453858736493302 0.9744983046248171 0.5484853257581203
  0.603461643169586 0.42310858396221174]
 [0.46754409134685826 0.6862421689590344 0.31777329745631644
  0.645917470955291 0.9272017795702548]
 [0.579811324731481 0.897137014040091 0.38006420057251045
  0.4020181772043969 0.2415441514994412]
 [0.5162863424158166 0.6507114253545695 0.09850962584604639
  0.6688443791040526 0.2356609722065558]
 [0.02739413505943178 0.30925154849289127 0.1959723922229828
  0.646689743056504 0.7993930821446444]
 [0.7349739458520681 0.9389005815514971 0.6612016992683768
  0.07191290357810398 0.537290170436649]
 [0.0550858743176722 0.18624052670524816 0.18391701594658627
  0.693676980234228 0.16369138072550693]
 [0.5336741942560962 0.09577291438590207 0.8956658008636414
  0.3570849378134764 0.7526841144070423]
 [0.29608228268283465 0.27874871093872733 0.13811452839805882
  0.8625898408251921 0.7381912547443896]
 [0.7850712316876535 0.21584826511623612 0.6583671831897339
  0.7856818172121444 0.003733566352210893]
 [0.9080499290170031 0.3191210318935962 0.27920477490365336
  0.6423499548142503 0.20627650942858233]
 [0.058275887103769075 0.3977515543861113 0.24442994800230367
  0.30015554672984146 0.5849070517632521]
 [0.467219150249655 0.25196175063927895 0.44725830592085714
  0.6039328697009941 0.5422360384781979]
 [0.0847717185977015 0.9599114961104934 0.7625480518868087
  0.014136178172979075 0.12133184850841416]
 [0.8433732695905898 0.11722375004697971 0.19141246982272653
  0.4888868326037221 0.8958480145577825]
 [0.8127974773388477 0.5853028854768588 0.11035266854015047
  0.5354552640910158 0.8147944917741538]
 [0.36136491034032703 0.05395331044500595 0.31552698339558083
  0.14474930612418313 0.06104886123356856]])

In [118]:
np.sum(a, axis='y')

GridArray(noname : [3.55667765 1.37199502 3.03844765 2.62409244 3.04467881 2.50057487
 2.17001274 1.9787009  2.9442793  1.28261178 2.63488196 2.31372662
 2.44870206 2.3550022  1.58551999 2.31260811 1.94269929 2.53674434
 2.85870279 0.93664337])

In [74]:
a

GridArray(noname : [[0.51773758 0.74823268 0.84997121 0.85184049 0.01909704]
 [0.28253743 0.30784544 0.22770422 0.98598182 0.46702724]
 [0.97525613 0.4946641  0.61267015 0.30934819 0.13752603]
 [0.55435852 0.80860641 0.43295254 0.06895191 0.85214425]
 [0.65533697 0.21350804 0.03090373 0.36030182 0.34186608]
 [0.50001462 0.37613848 0.31386637 0.77219564 0.20419148]
 [0.9194679  0.20059369 0.23005956 0.49256711 0.93594675]
 [0.43993728 0.81945399 0.369958   0.24159017 0.7493914 ]
 [0.26918439 0.6402172  0.16347993 0.37682523 0.75812015]
 [0.03773657 0.10964931 0.64876288 0.82756562 0.58489688]
 [0.27283382 0.11503791 0.44223876 0.57243144 0.17301331]
 [0.9611815  0.51623915 0.17170834 0.14321692 0.69130622]
 [0.73995773 0.93213192 0.73378686 0.39790764 0.72997257]
 [0.76638811 0.14951349 0.07727665 0.26727647 0.5371849 ]
 [0.05115629 0.69806089 0.01300415 0.0436297  0.18777605]
 [0.45762727 0.02551831 0.55151294 0.56075124 0.48050683]
 [0.29909592 0.07054671 0.32693787 0.58676342 0.70913594]
 [0.7766958  0.36543805 0.18194456 0.79364933 0.85188221]
 [0.04838825 0.70974108 0.36097104 0.17702063 0.75323571]
 [0.30013397 0.52159634 0.59489309 0.32864983 0.72589696]])

In [86]:
np.log10(np.exp(np.fabs(a)))

GridArray(noname : [[0.22485057340696105 0.3249533232737013 0.36913780491396725
  0.36994962261488973 0.00829373754378401]
 [0.12270444659976579 0.13369557558048423 0.09889068798507201
  0.42820646380386096 0.2028273512395685]
 [0.4235483557065706 0.2148298880982494 0.26607926735869525
  0.13434820988558682 0.05972679624309248]
 [0.24075484581278753 0.351173303742206 0.18802889817766197
  0.029945435964339878 0.3700815470458383]
 [0.28460922783743825 0.09272536463697129 0.013421318109416727
  0.1564770930458578 0.14847055095605186]
 [0.21715359127020015 0.16335486414249478 0.13631043233705392
  0.3353603047225876 0.08867923476400005]
 [0.3993198370007235 0.08711673054219356 0.0999135968585721
  0.2139191783039576 0.40647650695405796]
 [0.19106233356141253 0.3558843459904716 0.16067072005780647
  0.10492127661206864 0.32545655029859516]
 [0.11690529639697371 0.27804279639257545 0.07099843094402339
  0.16365311836500826 0.32924739659515684]
 [0.0163887837108065 0.04762008824362188 0.28175413706858604
  0.35940718222910234 0.2540174853128707]
 [0.11849022453056238 0.04996032868393072 0.19206185410262852
  0.24860381554070338 0.07513872751951439]
 [0.41743582081410946 0.2241998156449911 0.07457198558205708
  0.062198318057696704 0.30023047806441394]
 [0.32135955947589356 0.4048197486151405 0.31867958452476514
  0.17280909188028432 0.31702305979723466]
 [0.33283812804593327 0.06493288377642908 0.033560821665777056
  0.11607669504815842 0.23329643779630385]
 [0.02221689259049466 0.30316399229867724 0.005647628456936003
  0.018948136302322637 0.08155010124673853]
 [0.19874500008830998 0.01108245922370207 0.2395190245734154
  0.24353116783443707 0.2086814641642836]
 [0.12989570700283454 0.030638048020145386 0.14198731414639193
  0.25482811745320033 0.3079738256804699]
 [0.3373147018446848 0.1587077291142234 0.07901751824206552
  0.3446775255150732 0.36996774139488325]
 [0.02101475117370505 0.30823663366684395 0.15676772918569287
  0.07687908435120619 0.3271261145163018]
 [0.1303465249891242 0.2265264134452834 0.2583587868349666
  0.14273080666609408 0.31525304231369056]])

ValueError: not enough values to unpack (expected 2, got 1)

GridArray(noname : [ 0.94029067  1.73231065  2.48200734  3.06721417  3.55667765  3.63390926
  4.49706259  4.56963908  4.86852843  4.92867266  5.88463785  6.17367734
  6.89154995  7.45661246  7.96712032  8.0416589   9.01615721  9.56464253
 10.16810418 10.59121276 11.05875685 11.74499902 12.06277232 12.70868979
 13.63589157 14.21570289 15.11283991 15.49290411 15.89492229 16.13646644
 16.65275278 17.30346421 17.40197383 18.07081821 18.30647918 18.33387332
 18.64312487 18.83909726 19.485787   20.28518008 21.02015403 21.95905461
 22.62025631 22.69216921 23.22945938 23.28454526 23.47078578 23.6547028
 24.34837978 24.51207116 25.04574536 25.14151827 26.03718407 26.39426901
 27.14695312 27.44303541 27.72178412 27.85989865 28.72248849 29.46067974
 30.24575097 30.46159924 31.11996642 31.90564824 31.9093818  32.81743173
 33.13655277 33.41575754 34.0581075  34.264384   34.32265989 34.72041145
 34.96484139 35.26499694 35.84990399 36.31712314 36.56908489 37.0163432
 37.62027607 38.16251211 38.247283

In [124]:
np.cumsum(a, axis='y')

GridArray(noname : [[0.94029067 1.73231065 2.48200734 3.06721417 3.55667765]
 [0.07723162 0.94038494 1.01296143 1.31185079 1.37199502]
 [0.95596518 1.24500467 1.96287729 2.5279398  3.03844765]
 [0.07453859 1.04903689 1.59752222 2.20098386 2.62409244]
 [0.46754409 1.15378626 1.47155956 2.11747703 3.04467881]
 [0.57981132 1.47694834 1.85701254 2.25903072 2.50057487]
 [0.51628634 1.16699777 1.26550739 1.93435177 2.17001274]
 [0.02739414 0.33664568 0.53261808 1.17930782 1.9787009 ]
 [0.73497395 1.67387453 2.33507623 2.40698913 2.9442793 ]
 [0.05508587 0.2413264  0.42524342 1.1189204  1.28261178]
 [0.53367419 0.62944711 1.52511291 1.88219785 2.63488196]
 [0.29608228 0.57483099 0.71294552 1.57553536 2.31372662]
 [0.78507123 1.0009195  1.65928668 2.4449685  2.44870206]
 [0.90804993 1.22717096 1.50637574 2.14872569 2.3550022 ]
 [0.05827589 0.45602744 0.70045739 1.00061294 1.58551999]
 [0.46721915 0.7191809  1.16643921 1.77037208 2.31260811]
 [0.08477172 1.04468321 1.80723127 1.82136744 1.94269929]
 [0.84337327 0.96059702 1.15200949 1.64089632 2.53674434]
 [0.81279748 1.39810036 1.50845303 2.0439083  2.85870279]
 [0.36136491 0.41531822 0.7308452  0.87559451 0.93664337]])

In [125]:
np.std(a, axis='y')[::-2]

GridArray(noname : [0.12827470473623956 0.3213092738912151 0.11911509072123737
 0.2646902352754195 0.2838177495545586 0.22383452930485317
 0.28599916428014227 0.22577513086618847 0.2905352632778086
 0.30748783600508384])

In [126]:
a[a > 0.5] *= 10

In [127]:
a.T

GridArray(noname : [[9.40290675e+00 7.72316165e-02 9.55965183e+00 7.45385874e-02
  4.67544091e-01 5.79811325e+00 5.16286342e+00 2.73941351e-02
  7.34973946e+00 5.50858743e-02 5.33674194e+00 2.96082283e-01
  7.85071232e+00 9.08049929e+00 5.82758871e-02 4.67219150e-01
  8.47717186e-02 8.43373270e+00 8.12797477e+00 3.61364910e-01]
 [7.92019973e+00 8.63153328e+00 2.89039492e-01 9.74498305e+00
  6.86242169e+00 8.97137014e+00 6.50711425e+00 3.09251548e-01
  9.38900582e+00 1.86240527e-01 9.57729144e-02 2.78748711e-01
  2.15848265e-01 3.19121032e-01 3.97751554e-01 2.51961751e-01
  9.59911496e+00 1.17223750e-01 5.85302885e+00 5.39533104e-02]
 [7.49696692e+00 7.25764869e-02 7.17872614e+00 5.48485326e+00
  3.17773297e-01 3.80064201e-01 9.85096258e-02 1.95972392e-01
  6.61201699e+00 1.83917016e-01 8.95665801e+00 1.38114528e-01
  6.58367183e+00 2.79204775e-01 2.44429948e-01 4.47258306e-01
  7.62548052e+00 1.91412470e-01 1.10352669e-01 3.15526983e-01]
 [5.85206834e+00 2.98889356e-01 5.65062509e+00 6.03461643e+00
  6.45917471e+00 4.02018177e-01 6.68844379e+00 6.46689743e+00
  7.19129036e-02 6.93676980e+00 3.57084938e-01 8.62589841e+00
  7.85681817e+00 6.42349955e+00 3.00155547e-01 6.03932870e+00
  1.41361782e-02 4.88886833e-01 5.35455264e+00 1.44749306e-01]
 [4.89463471e-01 6.01442301e-02 5.10507856e+00 4.23108584e-01
  9.27201780e+00 2.41544151e-01 2.35660972e-01 7.99393082e+00
  5.37290170e+00 1.63691381e-01 7.52684114e+00 7.38191255e+00
  3.73356635e-03 2.06276509e-01 5.84907052e+00 5.42236038e+00
  1.21331849e-01 8.95848015e+00 8.14794492e+00 6.10488612e-02]])

In [48]:
a[3:5]

GridArray(noname : [[ 9.52798582 43.4973796   9.34051829  6.89698967  5.99668414]
 [ 8.37992184  7.58680271 23.85570971  8.27163313  6.21833324]])

In [52]:
np.sum(a, axis=0)

GridArray(noname : [256.35961124 288.31803594 377.4480668  205.9102254  363.36298254])

In [54]:
a * 2

GridArray(noname : [[45.47811478 45.706479    0.52845548 42.12316125 14.2766544 ]
 [11.25904402 11.77017832 79.70579063 86.53393305 92.16097635]
 [14.20611154 13.87158392 78.48376504  0.93997064 19.88195884]
 [19.05597164 86.99475919 18.68103659 13.79397933 11.99336827]
 [16.75984368 15.17360543 47.71141942 16.54326626 12.43666647]
 [65.21116424 22.19768134 15.70783322 15.89429074 16.41839842]
 [15.53873813 96.26061262 13.53151367 19.16121652 66.00694125]
 [40.03123255 14.77953077 45.29566493 70.67184211 68.34401182]
 [93.63028731  0.74711847 14.97870028 10.06730778 17.19575213]
 [10.42539435 11.57627994 18.9562908  18.98394774 55.76341815]
 [ 0.9704821  18.63989469 30.72068634 14.76564748 39.60688172]
 [18.55220009 14.84798858 70.31710629 11.22818099 15.97927864]
 [15.91020629  0.60473726 82.87437699 18.49549445 38.3789323 ]
 [29.68042017 13.36815733 15.397396   12.07440607 14.81297628]
 [19.29783481 15.93135102 21.73173143 13.55329291 19.02303471]
 [13.07343232 13.25273764 46.39977999 17.68788222 19.95362998]
 [10.72137865 59.95912198 12.63757904  0.83001963 89.42893959]
 [14.0347887   0.25018907 14.05504142 17.04126729 64.77579693]
 [16.94648697 52.79636609 73.24401862  0.7501324  18.62083887]
 [41.93609013 67.9076992  53.93794742 10.68121193 31.66750996]])

In [55]:
m = np.ma.masked_array(np.arange(10))

In [56]:
m.mask = m < 6

In [57]:
(m * 3).data

array([ 0,  1,  2,  3,  4,  5, 18, 21, 24, 27])

In [58]:
# add something
g['a'] = np.random.rand(g.grid.size).reshape(g.shape)

TypeError: data type not understood

In [100]:
np.asanyarray(g['a'])

array(GridData(Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)
[]), dtype=object)

In [32]:
g

GridData(Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)
[GridArray(a : [[0.92923727 0.66677596 0.23727435 0.1610907  0.01653312]
 [0.55190353 0.27774722 0.29892989 0.93888069 0.85850405]
 [0.73551706 0.35244653 0.8760508  0.21956474 0.53441049]
 [0.15723997 0.08435455 0.88621504 0.04831482 0.71454138]
 [0.85049881 0.99898884 0.52455096 0.7870131  0.69769233]
 [0.55569202 0.47328259 0.70182388 0.97605759 0.97067788]
 [0.35147541 0.53804803 0.42583771 0.34038949 0.67097437]
 [0.99991814 0.40016164 0.9862341  0.22136795 0.00428525]
 [0.1870811  0.55282106 0.89642015 0.02093399 0.89793334]
 [0.32208858 0.86061124 0.16765693 0.39742282 0.26526869]
 [0.55569622 0.82761335 0.09299961 0.60893835 0.49450812]
 [0.35534096 0.54596017 0.43240258 0.9995946  0.32889435]
 [0.9596192  0.34237546 0.67684045 0.36497417 0.14907469]
 [0.33104808 0.03411093 0.13289779 0.8052429  0.65576376]
 [0.66148267 0.397798   0.65264809 0.14355531 0.58967196]
 [0.22599018 0.5112301  0.55603438 0.66878642 0.75357486]
 [0.97331045 0.6453644  0.74637954 0.34437067 0.37256701]
 [0.55422566 0.43232625 0.94590443 0.28158927 0.98584402]
 [0.76719059 0.269261   0.28188932 0.52344498 0.06515638]
 [0.25834844 0.93810894 0.97695424 0.33338629 0.58261418]]), GridArray(b : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]])])

In [33]:
g['b'] = np.ones(g.shape)

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 b [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
finalize


In [34]:
g.shape

(20, 5)

In [35]:
g['b'].T

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 b b : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
finalize
new  <class 'pynocular.griddata.GridArray'> (points) [0 1 2 3 4]
(edges)  None
(nbins)  5
(points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5

GridArray(b : b : [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]])

In [42]:
np.sin(a).grid

ufunc
() {}


Grid(
Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5),)

In [43]:
a = g['a']

new  <class 'pynocular.griddata.GridArray'> (points) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(edges)  [[-0.5  0.5]
 [ 0.5  1.5]
 [ 1.5  2.5]
 [ 2.5  3.5]
 [ 3.5  4.5]
 [ 4.5  5.5]
 [ 5.5  6.5]
 [ 6.5  7.5]
 [ 7.5  8.5]
 [ 8.5  9.5]
 [ 9.5 10.5]
 [10.5 11.5]
 [11.5 12.5]
 [12.5 13.5]
 [13.5 14.5]
 [14.5 15.5]
 [15.5 16.5]
 [16.5 17.5]
 [17.5 18.5]
 [18.5 19.5]]
(nbins)  20
(points) [0 1 2 3 4]
(edges)  None
(nbins)  5 a a : [[0.92923727 0.66677596 0.23727435 0.1610907  0.01653312]
 [0.55190353 0.27774722 0.29892989 0.93888069 0.85850405]
 [0.73551706 0.35244653 0.8760508  0.21956474 0.53441049]
 [0.15723997 0.08435455 0.88621504 0.04831482 0.71454138]
 [0.85049881 0.99898884 0.52455096 0.7870131  0.69769233]
 [0.55569202 0.47328259 0.70182388 0.97605759 0.97067788]
 [0.35147541 0.53804803 0.42583771 0.34038949 0.67097437]
 [0.99991814 0.40016164 0.9862341  0.22136795 0.00428525]
 [0.1870811  0.55282106 0.89642015 0.02093399 0.89793334]
 [0.32208858 0.86061124 0.167

In [48]:
a.view(np.ndarray)

[autoreload of pynocular.griddata failed: Traceback (most recent call last):
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    update_generic(old_obj, new_obj)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 289, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 331, in update_generic
    update(a, b)
  File "/home/peller/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 265, in update_function
    setattr(old, name, getattr(new, na

array([Axis("x",
points = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19]),
edges = edges: array([[-0.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  2.5],
       [ 2.5,  3.5],
       [ 3.5,  4.5],
       [ 4.5,  5.5],
       [ 5.5,  6.5],
       [ 6.5,  7.5],
       [ 7.5,  8.5],
       [ 8.5,  9.5],
       [ 9.5, 10.5],
       [10.5, 11.5],
       [11.5, 12.5],
       [12.5, 13.5],
       [13.5, 14.5],
       [14.5, 15.5],
       [15.5, 16.5],
       [16.5, 17.5],
       [17.5, 18.5],
       [18.5, 19.5]]))
nbins = 20),
       Axis("y",
points = array([0, 1, 2, 3, 4]),
edges = edges: None)
nbins = 5)], dtype=object)

In [ ]:
g['b'][g['a'] < 0.5] *= -1

In [ ]:
g

In [ ]:
g['a']

In [ ]:
np.sum(g['a'], axis='y')

In [ ]:
g[:,-2]

In [ ]:
g[::-1, ::-1]

In [ ]:
g[[0,3,5], 2:-1]

In [ ]:
g[0,0]

In [ ]:
g.grid.edges[0].max()

In [ ]:
np.mean(g['b'], axis='x') + np.std(g['a'], axis='x')

In [ ]:
g['c'] = np.sqrt(g['x']) * np.sqrt(g['y'])

In [ ]:
g.plot('c', cbar=True)

In [ ]:
g['m'] = np.arange(g.grid.size * 3).reshape(g.shape + (-1,))

In [ ]:
g.plot('m') #it's interpreted as an RGB image, since the excess dimension is 3

In [ ]:
g['m'][:,:,0]

In [ ]:
g[:,3]

In [ ]:
g['m']

In [ ]:
g.T[:,3:5]['m']

In [ ]:
np.sum(g)

In [ ]:
np.sum(g, axis=(0))

# Stuff to fix

In [ ]:
np.sum(g['m'], axis=(0,1))

In [ ]:
# because of this
np.sum(g['m'], axis=-1).grid

In [ ]:
np.sum(g['m'], axis=-1)

In [ ]:
1 - 3 * g['a']

In [ ]:
2 ** g['a']

In [ ]:
g['a']

In [ ]:
g['a']

In [ ]:
a = g['a']

In [ ]:
a.T

In [ ]:
np.mean(a, axis='x')

In [ ]:
a

In [ ]:
from scipy import ndimage

In [ ]:
ndimage.gaussian_filter(a, sigma=1)

In [ ]:
np.median(a)

In [ ]:
np.cumsum(a)

In [ ]:
a.dtype

In [ ]:
np.sin(a)

In [ ]:
np.dot(a,a.T)

In [ ]:
b = a.values

In [ ]:
np.dot(b,b.T)

In [19]:
l = range(3)

In [20]:
l.next()

AttributeError: 'range' object has no attribute 'next'

In [128]:
from collections import OrderedDict

In [131]:
o = OrderedDict(a=12, b=23)

In [134]:
len(o)

2

In [140]:
for i in o.values():
    print(i)

12
23


In [141]:
o.keys()

odict_keys(['a', 'b'])

In [145]:
o.get()

<function OrderedDict.get(key, default=None, /)>

In [144]:
o.

OrderedDict()