In [1]:
%reload_ext autoreload
%autoreload 2
import numpy as np
import pynocular as pn
from matplotlib import pyplot as plt

In [2]:
g = pn.GridData(x=np.arange(11), y=np.arange(6))

In [3]:
g

GridData(Grid(
Dimension("x",
points = None,
edges = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))
nbins = 10),
Dimension("y",
points = None,
edges = array([0, 1, 2, 3, 4, 5]))
nbins = 5),)
OrderedDict())

In [4]:
# add something
g['a'] = np.random.rand(g.grid.size).reshape(g.shape)

In [5]:
g

GridData(Grid(
Dimension("x",
points = None,
edges = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))
nbins = 10),
Dimension("y",
points = None,
edges = array([0, 1, 2, 3, 4, 5]))
nbins = 5),)
OrderedDict([('a', array([[0.6817666 , 0.98032313, 0.11875093, 0.25843633, 0.67634892],
       [0.76474281, 0.5534844 , 0.57930991, 0.85986444, 0.67788916],
       [0.12103911, 0.12934866, 0.35274664, 0.14437848, 0.54647122],
       [0.35025073, 0.07893179, 0.07555533, 0.35597405, 0.12151858],
       [0.55967062, 0.13123896, 0.59686083, 0.48740149, 0.10934676],
       [0.85273984, 0.66401539, 0.30492486, 0.16957006, 0.60394058],
       [0.34306658, 0.73807996, 0.03271872, 0.98783162, 0.99035   ],
       [0.18650806, 0.2605788 , 0.92035236, 0.86155657, 0.49813536],
       [0.57438266, 0.45402796, 0.00583031, 0.86201915, 0.79707086],
       [0.92574597, 0.09283835, 0.87657422, 0.26073169, 0.39563669]]))]))

In [6]:
g['b'] = np.ones(g.shape)

In [7]:
g

GridData(Grid(
Dimension("x",
points = None,
edges = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))
nbins = 10),
Dimension("y",
points = None,
edges = array([0, 1, 2, 3, 4, 5]))
nbins = 5),)
OrderedDict([('a', array([[0.6817666 , 0.98032313, 0.11875093, 0.25843633, 0.67634892],
       [0.76474281, 0.5534844 , 0.57930991, 0.85986444, 0.67788916],
       [0.12103911, 0.12934866, 0.35274664, 0.14437848, 0.54647122],
       [0.35025073, 0.07893179, 0.07555533, 0.35597405, 0.12151858],
       [0.55967062, 0.13123896, 0.59686083, 0.48740149, 0.10934676],
       [0.85273984, 0.66401539, 0.30492486, 0.16957006, 0.60394058],
       [0.34306658, 0.73807996, 0.03271872, 0.98783162, 0.99035   ],
       [0.18650806, 0.2605788 , 0.92035236, 0.86155657, 0.49813536],
       [0.57438266, 0.45402796, 0.00583031, 0.86201915, 0.79707086],
       [0.92574597, 0.09283835, 0.87657422, 0.26073169, 0.39563669]])), ('b', array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]]))]))

In [8]:
g['a'].T

GridArray(a : [[0.6817666  0.76474281 0.12103911 0.35025073 0.55967062 0.85273984
  0.34306658 0.18650806 0.57438266 0.92574597]
 [0.98032313 0.5534844  0.12934866 0.07893179 0.13123896 0.66401539
  0.73807996 0.2605788  0.45402796 0.09283835]
 [0.11875093 0.57930991 0.35274664 0.07555533 0.59686083 0.30492486
  0.03271872 0.92035236 0.00583031 0.87657422]
 [0.25843633 0.85986444 0.14437848 0.35597405 0.48740149 0.16957006
  0.98783162 0.86155657 0.86201915 0.26073169]
 [0.67634892 0.67788916 0.54647122 0.12151858 0.10934676 0.60394058
  0.99035    0.49813536 0.79707086 0.39563669]])

In [9]:
g['b'][g['a'] < 0.5]

GridArray(b : [[-- -- 1.0 1.0 --]
 [-- -- -- -- --]
 [1.0 1.0 1.0 1.0 --]
 [1.0 1.0 1.0 1.0 1.0]
 [-- 1.0 -- 1.0 1.0]
 [-- -- 1.0 1.0 --]
 [1.0 -- 1.0 -- --]
 [1.0 1.0 -- -- 1.0]
 [-- 1.0 1.0 -- --]
 [-- 1.0 -- 1.0 1.0]])

In [10]:
g['b'][g['a'] < 0.5] *= -1

In [11]:
g['b']

GridArray(b : [[ 1.  1. -1. -1.  1.]
 [ 1.  1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.]
 [-1. -1. -1. -1. -1.]
 [ 1. -1.  1. -1. -1.]
 [ 1.  1. -1. -1.  1.]
 [-1.  1. -1.  1.  1.]
 [-1. -1.  1.  1. -1.]
 [ 1. -1. -1.  1.  1.]
 [ 1. -1.  1. -1. -1.]])

In [12]:
np.sum(g['a'], axis='y')

GridArray(a : [2.71562591 3.43529072 1.29398411 0.98223048 1.88451866 2.59519074
 3.09204689 2.72713116 2.69333095 2.55152692])

In [13]:
g[:,-2]

GridData(Grid(
Dimension("x",
points = None,
edges = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))
nbins = 10),)
OrderedDict([('a', array([0.25843633, 0.85986444, 0.14437848, 0.35597405, 0.48740149,
       0.16957006, 0.98783162, 0.86155657, 0.86201915, 0.26073169])), ('b', array([-1.,  1., -1., -1., -1., -1.,  1.,  1.,  1., -1.]))]))

In [14]:
g[::-1, ::-1]

GridData(Grid(
Dimension("x",
points = None,
edges = array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0]))
nbins = 10),
Dimension("y",
points = None,
edges = array([5, 4, 3, 2, 1, 0]))
nbins = 5),)
OrderedDict([('a', array([[0.39563669, 0.26073169, 0.87657422, 0.09283835, 0.92574597],
       [0.79707086, 0.86201915, 0.00583031, 0.45402796, 0.57438266],
       [0.49813536, 0.86155657, 0.92035236, 0.2605788 , 0.18650806],
       [0.99035   , 0.98783162, 0.03271872, 0.73807996, 0.34306658],
       [0.60394058, 0.16957006, 0.30492486, 0.66401539, 0.85273984],
       [0.10934676, 0.48740149, 0.59686083, 0.13123896, 0.55967062],
       [0.12151858, 0.35597405, 0.07555533, 0.07893179, 0.35025073],
       [0.54647122, 0.14437848, 0.35274664, 0.12934866, 0.12103911],
       [0.67788916, 0.85986444, 0.57930991, 0.5534844 , 0.76474281],
       [0.67634892, 0.25843633, 0.11875093, 0.98032313, 0.6817666 ]])), ('b', array([[-1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1., -1.,  1.],
       [-1.,  1.,  1., -1., -1.],
       [ 1.,  1., -1.,  1., -1.],
       [ 1., -1., -1.,  1.,  1.],
       [-1., -1.,  1., -1.,  1.],
       [-1., -1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1., -1., -1.,  1.,  1.]]))]))

In [15]:
g[0,0]

{'a': 0.6817665952128579, 'b': 1.0}

In [16]:
np.mean(g['b'], axis='x') + np.std(g['a'], axis='x')

GridArray(b : [0.46341868 0.10148348 0.12447477 0.11548052 0.46339888])

In [17]:
g['m'] = np.arange(g.grid.size * 3).reshape(g.shape + (3,))

In [23]:
g[:,3]

GridData(Grid(
Dimension("x",
points = None,
edges = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))
nbins = 10),)
OrderedDict([('a', array([0.25843633, 0.85986444, 0.14437848, 0.35597405, 0.48740149,
       0.16957006, 0.98783162, 0.86155657, 0.86201915, 0.26073169])), ('b', array([-1.,  1., -1., -1., -1., -1.,  1.,  1.,  1., -1.])), ('m', array([[  9,  10,  11],
       [ 24,  25,  26],
       [ 39,  40,  41],
       [ 54,  55,  56],
       [ 69,  70,  71],
       [ 84,  85,  86],
       [ 99, 100, 101],
       [114, 115, 116],
       [129, 130, 131],
       [144, 145, 146]]))]))

# Stuff to fix

In [27]:
g['m']

GridArray(m : [[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]]

 [[ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]]

 [[ 30  31  32]
  [ 33  34  35]
  [ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]]

 [[ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]
  [ 54  55  56]
  [ 57  58  59]]

 [[ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]
  [ 72  73  74]]

 [[ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]]

 [[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]]

 [[105 106 107]
  [108 109 110]
  [111 112 113]
  [114 115 116]
  [117 118 119]]

 [[120 121 122]
  [123 124 125]
  [126 127 128]
  [129 130 131]
  [132 133 134]]

 [[135 136 137]
  [138 139 140]
  [141 142 143]
  [144 145 146]
  [147 148 149]]])

In [26]:
np.sum(g['m'], axis=(0,1))

TypeError: list indices must be integers or slices, not tuple

In [28]:
np.sum(g['m'], axis=-1)

IndexError: list index out of range

GridArray(m : [[  3  12  21  30  39]
 [ 48  57  66  75  84]
 [ 93 102 111 120 129]
 [138 147 156 165 174]
 [183 192 201 210 219]
 [228 237 246 255 264]
 [273 282 291 300 309]
 [318 327 336 345 354]
 [363 372 381 390 399]
 [408 417 426 435 444]])